### ISSUE TITLE
Account-independent workers

### ISSUE THREAD

**Issue by KrishnaPG** [vsivsi/meteor-job-collection#100]
How to setup workers that are account-invariant. For example, I have one worker that I would like to take care of all jobs of one type, irrespective of who created it. Because in my case the owner does not matter.

How to achieve it (without loosening up the job management security)? That is, workers should not have to worry about security, while users from the front-end should have the regular job creation/management restrictions.

I am using a nodejs worker and not using any ddp login mechanism.

I see in the server side code example, there is `myJobs.allow` but it is not clear which permissions to set to what so that this can be achieved.

Also, in the playground example code, the queue name is `queue` but the node js worker is doing `ddp.observe('queue.jobs')`  (does it mean I have to append `.jobs` if I change the queue name to something else)?

Thanks for any info on these.

**Comment by vsivsi** [comment]
If you are truly using no authentication (hopefully on a private subnet!) the you can just provide an allow function that always returns `true`.

Yes, by default the underlying collection ends in `.jobs`. Job-collection in the meteor environment hides this from you, but when using nodejs+DDP you need to specify it.  Or alternatively you can use the `noCollectionSuffix` option when you create your collection, and then it won't do that.

**Comment by KrishnaPG** [comment]
Thanks. That helped.
