### ISSUE TITLE
How to increase socket connection timeout

### ISSUE THREAD

**Issue by KrishnaPG** [vsivsi/meteor-job-collection#105]
The sample (the nodejs example) is timing out for short duration and reconnecting the meteor server with below output:
````
Socket closed! 1000
Connected 
allJobs Ready!
clientStats Ready!
````
How to increase this socket timeout. Looks like ddp is closing the socket - where should it be configured to make it stay for longer time?

**Comment by vsivsi** [comment]
Do you know which end is timing out?  The node DDP client uses [faye-websocket](https://www.npmjs.com/package/faye-websocket) which doesn't have any obvious timeout setting. The best strategy may be to write a handler for the emitted `'close'` event and reconnect (you'll need that anyway for long running connections to handle other cases...)

**Comment by KrishnaPG** [comment]
Thank you.

Its the client side (the nodejs worker) - because I am putting breakpoint and trying to step-in through the code, verifying the variables along. By the time the step execution reaches some interesting piece of code, the ddp is timing out (and the job logs / messages do not get deliver to the meteor server). Hence trying to see if there is some way of making the socket/connection stay longer. 

Yes, the code is reconnecting automatically, but in the debugging I am loosing the context. .
