### ISSUE TITLE
Can't create a new Job and get TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by a4xrbj1** [vsivsi/meteor-job-collection#106]
I've tried for the whole day but I cannot get an entry in the jobs collection I created. Here's the code I've added specifically for the package, maybe I'm overlooking something (must be as no one else has such a problem).

This is jobs.js in the collections folder:

    if (Meteor.isServer) {
    Jobs = new JobCollection('jobs');

    Meteor.startup(function () {
        console.log("JobServer started: " + Jobs.startJobServer());
        return;
    });
};

The server report true so is running. The following code is in a separate file and is copied directly from the documentation of the vsivsi:job-collection package:

    var job = new Job(Jobs, 'sendEmail', // type of job
                                // Job data that you define, including anything the job
                                // needs to complete. May contain links to files, etc...
                                {
                                    address: 'bozo@clowns.com',
                                    subject: 'Critical rainbow hair shortage',
                                    message: 'LOL; JK, KThxBye.'
                                }
                            );

                            // Set some properties of the job and then submit it
    job.priority('normal')
      .retry({ retries: 5,
        wait: 15*60*1000 })  // 15 minutes between attempts
      .delay(60*60*1000)     // Wait an hour before first try
      .save();               // Commit it to the server

    // Now that it's saved, this job will appear as a document
    // in the myJobs Collection, and will reactively update as
    // its status changes, etc.

                            console.log ("Job inserted: " + job._id);

Console:
**Job inserted: undefined**

If I change the last line (console.log) to this:

    console.log ("Job inserted: " + JSON.stringify(job));

then console is giving me the following error message:
**TypeError: Converting circular structure to JSON**

Which is strange as it's for sure not a circular structure (see above). Like I said I copied the code directly from the documentation 1:1, so I don't understand why it's not working (only difference is that I named my job collection differently and left out the .allow and Meteor.publish part.

I've also checked the MongoDB directly via console and it doesn't return any document:
> db.jobs.find()

Any help is highly appreciated, I'm ready to throw the towel and give up on this package but it must be something simple that I overlooked. Thanks!

**Comment by vsivsi** [comment]
Hi, it would helpful if you could create and share a git repo with your exact Meteor project that you are seeing this issue in. That way I can take a look using exactly the same code you are using. 

You can also take a look at the working code of the [sample app](https://github.com/vsivsi/meteor-job-collection-playground) to see what working code looks like. 

This is almost certainly something simple, but as I said, I can't really help debug if I don't have the full project so I can replication everything.

**Comment by a4xrbj1** [comment]
Hi Vaughn,

I'm not on Git, my repo is on Bitbucket in a private repo. If you can send me an email (my profile has my email address visible) then I can add you to the repo.

I've taken a look at the sample app before but it's all in coffee which I don't understand (I only drink it once in a while LOL).

Please do note that the above code is all that I've added in regards to your package. Thanks for your quick response BTW, I know this isn't your day job so it's highly appreciated!

**Comment by vsivsi** [comment]
Okay, the issue is this... The job document as stored on the server needs to be accessed via an accessor function documented here: https://github.com/vsivsi/meteor-job-collection#jobdoc---anywhere

So in your code above:

```js
var result = job.priority('normal')
  .retry({ retries: 5,
    wait: 15*60*1000 })  // 15 minutes between attempts
  .delay(60*60*1000)     // Wait an hour before first try
  .save();               // Commit it to the server

// This works
console.log ("Job inserted: " + job.doc._id);
// And so does this:
console.log ("Job inserted: " + result);
```

The `.save()` is actually working, you just weren't looking in the right place for the results.

**Comment by vsivsi** [comment]
As an aside... The reason that `console.log ("Job inserted: " + JSON.stringify(job));` throws a TypeError is that job objects are pretty complicated and different from the "job document" that is stored in the database. You can see that by running:

```js
console.dir(job);
// vs
console.dir(job.doc);
```

**Comment by a4xrbj1** [comment]
Thanks Vaughn, so how can I access the jobs collection via the Mongo console?db.jobs.find().count()

**Comment by vsivsi** [comment]
By default JC collections end in `".jobs"` so if your JobCollection name is also `"jobs"` then:
```js
db.jobs.jobs.find().count()
```
