### ISSUE TITLE
ready-to-run hours ago but status is "waiting"

### ISSUE THREAD

**Issue by KrishnaPG** [vsivsi/meteor-job-collection#107]
Please refer the below screenshot. Any idea how this kind of situation can occur?
![image](https://cloud.githubusercontent.com/assets/4610831/9653248/d36543ec-523f-11e5-8da1-fc3f097fae47.png)

To give background, this is happening on a sample app running on local machine. The tasks were scheduled to run once per day, and they were running fine. Yesterday due to some outage, turned off the local machine and just now turned on and started the server and worker process again.

I was expecting to see that since the ready state has already reached hours ago, upon starting the server it would immediate schedule the job (that was overdue last night). But the status is still 'waiting'. 

Job promotion time is set to be 15 minutes (`myJobs.promote (1000 * 60 * 15)`).

Looks like it is waiting for additional 15 minutes *after startup* to promote the jobs (even the ones that are long due).

I think at the startup the jobs that are already meeting ready criteria should be immediately scheduled (and not be subject to further promote delays). Is there an option to control if jobs at server (re)start should be immediately scheduled (changed to ready state) or waited for further promote delay?

**Comment by vsivsi** [comment]
This looks like it may be a bug, I'll give it a closer look. I have never tested with suck long promote cycles. There's very little benefit to making the promote cycle being as long as 15 minutes, when 15 seconds would use only a tiny amount more system resources. But I agree that when a server restarts, it should immediately promote any jobs that became ready while it was down.

**Comment by vsivsi** [comment]
Fixed in v1.2.3
