### ISSUE TITLE
Way to defer job work to an external process?

### ISSUE THREAD

**Issue by jraede** [vsivsi/meteor-job-collection#111]
We're using this package for queuing messages which get sent via SMS using Twilio's API. Twilio doesn't give us the message status synchronously, but rather runs a webhook and hits our endpoint sometime later.

What we want to do is start the work for the message, but not actually run `done` or `fail` until we get the status back from Twilio (or, ideally, also if it reaches some configurable timeout). So something like `job.defer()` and then just let something explicitly call `job.done()` or `job.fail()` at a later time. It would essentially be pausing a job that is currently `running` so it could continue to work the other messages in the queue, but that's not allowed by the state machine logic.

How do you recommend approaching this? Is there functionality already in this package that we can use?

Thanks

**Comment by vsivsi** [comment]
How are you associating the external endpoint request with the partially completed job's `_id`?  So long as that mapping somehow exists, you can just recreate the job document in the endpoint handler code:

```js
// In endpoint handler code
var jobId;   // looked up from from endpoint request?
var jobSuccess;  // Also...

job = jc.getJob(jobId);  // Or add callback if not Meteor server...

if (jobSucceeds) {
   job.done(...);
} else {
   job.fail(...);
}
```

Alternatively, if the endpoint request contains information in the `job.data`...

```js
var query = {...};  // Mongo query to find the job
var jobSuccess;  // Also...

jobDoc = jc.findOne(query);
if (jobDoc) {
   job = new Job(jc, jobDoc);
   if (jobSucceeds) {
      job.done(...);
   } else {
      job.fail(...);
   }
}
```

**Comment by vsivsi** [comment]
The above all assumes that your endpoint handler is running on the Meteor server, or is a node program with a DDP connection to the server, and is using the `meteor-job` library to run the above code outside of Meteor.

**Comment by jraede** [comment]
I'm planning to just store a document somewhere with a `jobId` and `twilioMessageId` property and retrieve the job in the endpoint, like you have above. 

Anyway my understanding was that we need to run `job.done()` or `job.fail()` in the worker function that actually sends the message to Twilio, otherwise it wouldn't move on to process the next job. Is that correct? If that's the case then we'd have to run `job.done()` inside of there, and then `job.fail()` in the endpoint wouldn't be allowed since you can only fail a running job. Can you clarify?

**Comment by vsivsi** [comment]
Hi, no I don't think so.  `jc.processJobs()` only cares that its callback gets called before moving to request more work, it pays no attention to the status of the job itself

```javascript
// Jobs will auto-fail if Twilio doesn't call endpoint within 15 minutes... 
jc.processJobs('twilioSend', { workTimeout: 15*60*1000 }, function(job, cb) {  // Added callback
    var msgId = twilio.sendMessage(...);
    twilioCollection.insert({jobId:job._doc._id, twilioId:msgId});
    cb();
    // job is still "running" until twilio calls back. 
});
```

**Comment by jraede** [comment]
Oh, perfect. I'll try that. Thanks for the quick response!

cc @aldeed

**Comment by aldeed** [comment]
@jraede, OK, yeah maybe it was not calling the callback that caused the other queue to get stuck. I was thinking it was the done/fail calls.
