### ISSUE TITLE
Ensure that a job only runs once

### ISSUE THREAD

**Issue by teknetia** [vsivsi/meteor-job-collection#112]
Is it possible to ensure a job runs only once by settings something like the following or is there a different way that I am supposed to do it?

```
.repeat({
  repeats: 0
})
```

**Comment by vsivsi** [comment]
Jobs only run once by default.  When a new Job object is created, it is automatically initialized by calling `job.repeat()`. The default parameter for that call when omitted is `0`, which is equivalent to your code above.  So:

```js
// These are all the same... (job will run once, will not repeat)
job1 = new Job(jc, type, data);
job2 = new Job(jc, type, data).repeat();
job3 = new Job(jc, type, data).repeat(0);
job4 = new Job(jc, type, data).repeat({ repeats: 0 });
```

**Comment by teknetia** [comment]
Oh right, my mistake I think I have misread the documentation to say it always defaulted to repeating. Which now I think about it a little more makes zero sense! Cheers mate.
