### ISSUE TITLE
jobProgress failed (as job.done is executed before it)

### ISSUE THREAD

**Issue by a4xrbj1** [vsivsi/meteor-job-collection#114]
It's only a small irritation I would say but I have several cases when the last `jobProgress` (the one making it 100%) is executed it is done AFTER the `job.done` and hence I get the error message:

`jobProgress failed`

Not sure if that can be solved or omitted when the job is shown as completed.

**Comment by vsivsi** [comment]
Hi, Updating `job.progress()` is only valid on running jobs, and as you are seeing, will fail if called after `job.done()` or `job.fail()`.  I believe this to be the correct behavior...  

FYI, running `job.done()` automatically sets the progress to 100%, so there is no need for the "final" call to `job.progress()` to do that, which may reduce some of your irritation!

Also note that `job.log()` may be called at any time to add information about an existing job; before, during or after it is run.

**Comment by a4xrbj1** [comment]
Vaughn,

Maybe you misunderstood me. Job.progress is before the job.done in my code.

But I will check with an if clause if this is the last iteration and avoid
calling it.

**Comment by vsivsi** [comment]
Right, but are you running in an environment with Fibers, or alternatively calling `job.done()` inside the callback for `joc.progress()`?

Remote Meteor/DDP method calls are asynchronous.  So without either fibers or callbacks, the completion order of the following code is not strictly serial:

```js
\\ Without Fibers, this is not serial
job.progress(...);
job.done(...);

\\ This is
job.progress(..., function (err, res) {
    job.done(...);
});
```

**Comment by a4xrbj1** [comment]
I'm using it on the server. As I run this in a loop it's not possible to
call `job.done()` inside the callback for `job.progress()`.

However I managed it with an easy `if` clause checking if the `count`
variable is at the last run through the loop (as the number of loops is
fixed).

Thanks for your suggestions, Vaughn. I'm still learning the depths of sync
vs async, so that's a good reminder!

**Comment by vsivsi** [comment]
Hmm. Running in the Meteor server environment, which includes Fibers support, should make those calls (appear) synchronous.  I'd need to see your code to comment further, but you shouldn't be running into async issues on Meteor server unless you have code with improperly structured callbacks. Providing callbacks overrides the Fiber support...
