### ISSUE TITLE
Is it possible to delay jobs for a certain time after the dependent job has finished?

### ISSUE THREAD

**Issue by a4xrbj1** [vsivsi/meteor-job-collection#115]
Hi Vaughn,

I might stretch the current features a bit. I misunderstood `job.delay` and thought it would allow me to delay a job so that it starts in ms after the dependent job finished. But it's a delay based on when the job is being submitted.

Reason for this (new) feature is that I'm querying a third party website with a lot (means thousands) of GET queries and as those queries are all chained up (to start after the previous is finished) I would like to simulate a more human behavior and give the third party server a breather before firing the next query.

Is that possible with the current parameters? I've read through the excellent documentation again and I think it's not but happy to be profed wrong ;-)

Thanks in advance as usual

**Comment by vsivsi** [comment]
Hi, you are correct, `job.delay()` just sets the earliest time when a dependent job can run. 
What you are asking for would be a new feature. 

Can't you just simulate this by building the delay into e antecedent job?  If the first job always waits N seconds before calling `job.done()` haven't you achieved the same thing?  Or the worker could implement this as a configurable setting in its `data`.  If a `delay` attribute is present, then do a `setTimeout` before commencing with the actual work. 

I'm inclined to say that these simple approaches you can implement yourself will be more flexible than any new feature I might add to JC.  I'm open to your thoughts on this, but my philosophy for the design of JC has been to keep it lean and only do what is more difficult for the developer to achieve in other ways. This case doesn't feel like it meets that test.

**Comment by a4xrbj1** [comment]
Well Vaughn, we're talking here about a lot of jobs that are chained together. 
As in a couple thousand jobs. I have almost 44000 jobs to run for 7 users and 
3 of them have very little jobs, so the rest probably has 10000 jobs each.

If I understand you correctly this would only work with the very first job of 
the chain, not the remaining 9999 ones, right?

As many jobs are running in parallel in my worker app, I don't want to use a 
setTimeout that is blocking execution of any other job.

Andreas

**Comment by vsivsi** [comment]
Thinking about it a bit more... Both of the approaches above (waiting in the first or second worker) will work, but involve tying up a worker slot during the delay, which is suboptimal on a busy, capacity constrained system. 

There are other more involved approaches that could work, such as not using the dependent job mechanism at all, and just having the first job create the second one (requires permission) with the appropriate delay.  Or having it lookup the dependent job `_id` value(s) in its own job document, and creating job objects from that, and setting new delays on those job objects before finishing. So that would look something like:

```js

depId = job.doc.depends[0];  // Assumes 1 dependent job
// or loop over array for each dep job
depJob = jc.getJob(depId);
depJob.pause();
depJob.delay(...);
depJob.save();
// done with first job
job.done();
```

If I were to add this as a feature, this is effectively what I would do, add an option to `job.done` to add a delay to any dependent jobs before removing the dependency. It would be slightly more involved, because it would need to check that it wasn't causing any jobs to run *sooner* than they were originally scheduled.

**Comment by vsivsi** [comment]
@a4xrbj1  I've removed a bad suggestion from the previous post. It's been awhile since I've looked at this and I forgot that dependencies are stored in the dependent job's document. That makes this a job for the server, not the worker. If I have a spare hour in the next few days I'll prototype this on a branch for you to try out.

**Comment by a4xrbj1** [comment]
Wow Vaughn, you're really going the extra mile and I know this isn't your
day job. Thanks a lot, that would be wonderful!

**Comment by a4xrbj1** [comment]
Hi Vaughn,


correct me if I'm wrong but you haven't yet found time to add the above new feature, right? It would be really helpful for me as I'm throwing ten's of thousands jobs at this website to ease the load out a bit.

**Comment by vsivsi** [comment]
I'll look at doing this in the next week or so.  I've been completely slammed the past few weeks.

**Comment by vsivsi** [comment]
I just committed this on a branch here: https://github.com/vsivsi/meteor-job-collection/tree/delay_deps

There's a new option `delayDeps` for `job.done()`

Try it out and let me know how it goes.

**Comment by a4xrbj1** [comment]
Hi Vaughn,

was finally having time to test this. Well, I downloaded the zip file and I know I have to put it manually into my app folder. But where and what do I have to rename the folder? Right now it's called `meteor-job-collection-delay_deps`.

Can you help me with some instructions or point me at an article that highlights how to test a package? I've never done this and my experience with GitHub is very limited. Thanks!

**Comment by rhyslbw** [comment]
@a4xrbj1 Create a `/packages` dir in your app root (at the same level as `.meteor`) and move the unzipped directory there (the name should not matter). By default meteor will use a local package in this directory over a remote package as long as the version is either the same or greater in the current major release version.

**Comment by a4xrbj1** [comment]
Thanks!

**Comment by a4xrbj1** [comment]
There seems to be at least one file missing in the zip I downloaded:

    While building package vsivsi:job-collection:
    error: File not found: job/src/job_class.coffee

Am I doing something wrong or is the package not complete? Also, I'm not sure if I'm writing the correct syntax:

    job.done({ delayDeps: 10000 });

**Comment by vsivsi** [comment]
Rather than installing from a zip, you should just clone the package using git. 

```
git clone --recurse-submodules https://github.com/vsivsi/meteor-job-collection.git ./packages/jC
cd packages/jC
git checkout delay_deps
```

The missing file is because meteor-job-collection includes meteor-job as a git submodule, and that doesn't get bundled up in the repo zip files.

**Comment by rhyslbw** [comment]
Have you considered rigging meteor-job in as an npm dependency @vsivsi ?

**Comment by vsivsi** [comment]
I've considered it, but Meteor's npm support doesn't extend to the client, and the meteor-job package is required by both client and server.

**Comment by rhyslbw** [comment]
ah ok, maybe 1.3 will remove that as a blocker
https://github.com/meteor/meteor/blob/release-1.3/History.md#v13

**Comment by vsivsi** [comment]
This will be released today in 1.3.0 on Atmosphere

**Comment by a4xrbj1** [comment]
Thank you so much Vaughn for further developing your awesome package!

Andreas

**Comment by benlavalley** [comment]
Just updated to it via Git. I use this for handling all of my app's email and text messaging chat (Twilio+Mandrill integrated). Working nicely :) 

I wanted to pull it down to strip out any client components since I just use it at the server. Been on a mission lately to slim down my app.
