### ISSUE TITLE
Job.Progress does not update beyond initialization

### ISSUE THREAD

**Issue by Chugot** [vsivsi/meteor-job-collection#116]
Hello,

I'd like to start off by saying I appreciate all your work on this package, it works well and has also made my life much easier!

On to my issue, I am trying to utilize the Job.Progress feature to create a progress bar of sorts, however I am having difficulties in getting the progress to update (I am able to set it once initially but beyond that I have been unable to update it).

Here is a small snippet of my code:

    var newProcess = new Job(Processes,'startProcess',{"batchName": batchName, "jobRunID": instanceID, running:true});
    var avgRunTime;
    if(prevRunTime !== undefined) {
        avgRunTime = prevRunTime.batRunTime.avgRunTime.toFixed(0)
    }
    var progProc = newProcess.progress(0,Number(avgRunTime)+1);
    progProc.save();
    // progProc.progress(15,Number(avgRunTime)+1, function(error,result){if(error)  {logger.debug(error)};});
    // progProc.progress(20,Number(avgRunTime)+1)
    if(prevRunTime !== undefined) {
        var timer = 1;
        var intTimer = setInterval(function () {
            console.log(Number(avgRunTime) - 1);
            if (!(timer == avgRunTime - 1)) {
                progProc.progress(timer,Number(avgRunTime)+1)

                console.log("in interval");
            }
            else {
                console.log("clearing interval");
                clearInterval(intTimer);
            }
            timer++;
        }, 1000)
    }
	//progProc.progress(40,Number(avgRunTime)+1)

Essentially I am trying to use a timer to increment up to my previously calculated "average run time" to give an estimate of the total progress of the new job.

The initial call to newProcess.progress() does in fact set the total and completed, however once I am inside my timer loop, none of the progProc.progress() updates seem to work.  The couple lines of commented code before and after the timer were put in place to debug whether I could update progress at all (i.e. some kind of timing problem in my timer).  I have also tried updating the progress directly on the newProcess object without using the returned Job value and found the same issue.  I hope I am not missing something obvious, I tried to test as many variations as I could and I also did not see anything that stood out in the package code as causing problems.  Any assistance you can provide will be much appreciated, I could move this functionality out of JobCollection but because I have it available I would like to utilize it if possible.  Thanks in advance!

**Comment by vsivsi** [comment]
Hi, Once a job has been saved by calling `job.save()`, then its progress can only be updated if its status is `"running"`, or if it is `"waiting"` or `"ready"` it may be paused and then re-saved. This is necessary to keep the server in sync with the local job object.

If it is `"running"` and the code calling `job.progress()` is a worker (the normal case, e.g. obtained the Job object via `jc.processJobs()` or `jc.getWork()`) then everything should work as expected.

If you haven't already, I recommend checking out one of the sample apps, that have UI progress indicators:

https://github.com/vsivsi/meteor-job-collection-playground
https://github.com/vsivsi/meteor-file-job-sample-app

**Comment by vsivsi** [comment]
I mis-spoke above. You are correct, once you have saved a job, it must be running and you must have the valid `runId` (as a worker does) to update the job progress.  This is necessary for consistency.  If a job is cancelled, or fails on the server, but then is restarted/rerun, there may still be an old worker that tries to update its progress, even though there may now be a new worker. That is the purpose of the runId, to make sure that only the current valid worker can make changes to the status and progress of a running job.

**Comment by Chugot** [comment]
Thank you very much sir, I had thought the current state of my job satisfied all the requisites for updating progress that you described, but I do see that after saving my job inside of my "Job Creator" code I do not have the RunID available in the job object.  After moving my increment/timer logic into the actual worker code, I was able to properly increment the progress there.  Thanks again and keep up the good work!

**Comment by vsivsi** [comment]
@Chugot  Glad you got it straightened out.
