### ISSUE TITLE
_createLogEntry should be a extendable

### ISSUE THREAD

**Issue by mitar** [vsivsi/meteor-job-collection#120]
Currently it is a top-level static method. It would be great for it to be on a class somehow so that you could extend it to translate strings. (Or have some other function just to create strings.)

**Comment by vsivsi** [comment]
Can't you just define your own `_logEntries` Object with whatever translations/methods that you want?  That was my intention.  Oh, I see, you want to be able to use `_createLogEntry` in redefining `_logEntries`.  Yeah. That makes sense. This is another "will need to wait until January" level item though...

**Comment by mitar** [comment]
Or I would want to not have to redefine `_logEntries` but just extend `_createLogEntry` to map a given string to my own string, while leaving the rest as it is. The only one where this might be trickier is `failed`, so we might want to pass more data to it (everything what it is used to construct message in anonymous function there) or we should simply move the anonymous function also to the class. Something like `_createLogFailEntry` or something.

**Comment by vsivsi** [comment]
This will be in v1.3.0
