### ISSUE TITLE
Mistake in getWork documentation?

### ISSUE THREAD

**Issue by mitar** [vsivsi/meteor-job-collection#124]
> If maxJobs > 1 the result will be an array of job objects, otherwise it is a single job object, or undefined if no jobs were available

It seems that `getWork` returns always an array? I call without any special arguments, so `maxJobs` should be default 1, so it should be returning an object or undefined. But it is returning array.

**Comment by vsivsi** [comment]
A quick look at the code confirms that you are correct. I'll try to fix this in the next few days. Or if you put together a PR... :-)

**Comment by mitar** [comment]
Done: #125

**Comment by mitar** [comment]
Merged.
