### ISSUE TITLE
Switch default branch to 'dev' from 'master'

### ISSUE THREAD

**Issue by rhyslbw** [vsivsi/meteor-job-collection#126]
This should address a couple of issues:

1. PRs are opened against _dev_ by default
2. Documentation can then also just be pulled against _dev_ since that's the landing page for the repo GitHub url, avoiding the need to back merge after releasing.

I'd also suggest taking the opportunity to consider using [git-flow](http://danielkummer.github.io/git-flow-cheatsheet/). It's a nice guideline to follow, and keeps things nicely organised

**Comment by mitar** [comment]
But the issue is that then documentation people see in the README is from `dev` and not stable branch.

**Comment by rhyslbw** [comment]
true, and that evolves independently. Unless that's going to be managed elsewhere I guess keeping the master as the default is the only option.
