### ISSUE TITLE
Job is ready but not starting

### ISSUE THREAD

**Issue by mazing** [vsivsi/meteor-job-collection#127]
If I start a job with

    var job = new Job( Jobs, 'myMethod',
      {
        name: "some name",
        age: 32
      }
    ).priority( 'normal' ).retry(
      {
        retries: 5,
        wait: 15 * 60 * 1000 // 15 minutes between attempts
      }
    ).save();

it will just say `status=ready` but never `status=completed`.

How can I start the job?

**Comment by vsivsi** [comment]
Do you have any workers?

**Comment by vsivsi** [comment]
Also, you need to start the server queue. 

```
startJobServer();
```

**Comment by ThadeuLuz** [comment]
Im having a similar problem. At first I thought it was related do .depends(), but aparently can't restart a failed job at all. It just hangs waiting forever.

I created a tiny app to show what I mean, let me know if I am doing anything wrong.

app/hello.html 

    <head>
      <title>hello</title>
    </head>
    
    <body>
      {{> hello}}
    </body>
    
    <template name="hello">
      {{#each jobs}}
        <p> {{this._id}} | {{this.status}} </p>
      {{/each}}
      <br>
      <button>Add/Restart Job</button>
    </template>


app/hello.js

    myJobs = new JobCollection('queue');
    
    if (Meteor.isClient) {
      Template.hello.helpers({
        jobs: function () {
          return myJobs.find();
        }
      });
    
      Template.hello.events({
        'click button': function () {
          var job = myJobs.findOne();
          if (job) {
            myJobs.getJob(job._id, function (err, j) {
              j.restart();
            });
          } else {
            job = new Job(myJobs, 'fail', {});
            job.save();
          }
        }
    
      });
    }
    
    if (Meteor.isServer) {
    
      myJobs.allow({
        admin: function () { return true; }
      });
    
      myJobs.processJobs('fail', function (job, cb) {
        Meteor.setTimeout(function () {
          job.fail();
          cb();
        }, 5000)
      });
    
      Meteor.startup(function () {
        myJobs.startJobServer();
      });
    }

Just click the button, wait for the job to fail and then try to restart it.

Thanks

**Comment by vsivsi** [comment]
@mazing  Did this work for you?
