### ISSUE TITLE
Is there a right way to pass processed data from a job to its descendant?

### ISSUE THREAD

**Issue by ThadeuLuz** [vsivsi/meteor-job-collection#130]
The title says it all. Right now I'm doing this on the antecedent:

    Jobs.update(job._doc._id, { $set: {
      "data.stuffFound": 'stuff'
    }});

and then in the descendant

    Jobs.findOne(job._doc.resolved[0]).data.stuffFound

basically using it as a regular collection. It is working so far, but the fact that the docs says data can't be changed after job is created makes me wonder if there is a better way.

Thanks in advance. This package rocks!

**Comment by vsivsi** [comment]
Hi, there's no "official" way to do this. Although it would probably be more "normal" to write the results of a job using the `job.done(result)` pattern.  The result can then be read as:

```js

Jobs.findOne(job.doc.resolved[0]).result

```

 Another pattern I use is to "prearrange" an `_id` in another collection (like a [file-collection](https://github.com/vsivsi/meteor-file-collection)) where the result will be written. Just crate a new mongo ID, and then write it into the data of both jobs, and then the result / data connection is made out of band from the job-collection.  Obviously this is really the only way if the data to pass is > 15MB or so.

**Comment by ThadeuLuz** [comment]
Probably *result* is the way to go for me because the data is temporary.
Thanks

**Comment by ThadeuLuz** [comment]
Just a quick update:
I was having problems getting the descendant task to re-run after it had failed the first time, so I ended up just creating the second task ('descendant') right before the first ('atecedent') finishes. That way I can just add the temp data as usual, on the job.data. Saves me an update and a find.

**Comment by vsivsi** [comment]
Do you think there's a bug somewhere in retrying failed jobs that were initially delayed waiting for other jobs?  Can you elaborate a bit on the problems you saw?

**Comment by ThadeuLuz** [comment]
Hmm.. Now that you asked, there might be a bug, yes. Here's a simple code, see if you can reproduce:

    var shouldFail = true;

    Jobs.processJobs('j1', function (job, done) {
      job.done();
      done();
    });
    
    Jobs.processJobs('j2', function (job, done) {
      if (shouldFail) {
        shouldFail = false;
        job.fail();
      } else  {
        job.done();
      }
      done();
    });



Then just add jobs with dependency

    var j1 = new Job(Jobs, 'j1', {});
    j1.save();

    var j2 = new Job(Jobs, 'j2', {});
    j2.depends([j1]);
    j2.save();

When the second job fails for the first time, if you tell it to restart, it will just wait (for the first job?) forever.

**Comment by ThadeuLuz** [comment]
Nevermind. Just had to wait for about 5 minutes and the failed job started again.

**Comment by vsivsi** [comment]
Great! Thanks for reporting back.
