### ISSUE TITLE
Is it necessary to call job.done() when job.progress() is 100%?

### ISSUE THREAD

**Issue by a4xrbj1** [vsivsi/meteor-job-collection#135]
I'm currently using `job.progress()` to show progress of several iterations until it's 100% finished. Only in those cases I'm currently not using `job.done()` to finish a job.

My question is a `job.done()` automatically executed from the system when the job.progress() reaches 100% completion?

Otherwise I quickly have to change my code before putting more load on the job worker (not sure what consequences a missing `job.done()` would have (on the stack for example).

**Comment by vsivsi** [comment]
You must eventually call either `job.done()` or `job.fail()` on every job that is issued to a worker via `processJobs()` or `getWork()`.  If you don't, the job will become a "zombie" that never completes, or will be automatically failed and retried if you use the appropriate settings for auto-failing jobs when workers crash or lose connectivity. 

`job.progress()` is optional, is meant for logging and UI purposes, and has no effect on the actual completion of jobs.

**Comment by vsivsi** [comment]
I should also note that calling `job.done()` automatically sets the progress to 100% if it isn't already, but the opposite isn't true as I said above. So unless you have some UI that shows the progress value, or some other internal mechanism that does something with it, the there is no need to make progress calls at all.

**Comment by a4xrbj1** [comment]
Thanks Vaughn, will change my code immediately!

**Comment by a4xrbj1** [comment]
Well, the job executes are very complicated and computation intensive
function up to a couple hundred times. Keeping track of the progress is
crucial I think, at least for now (once I have my own admin console ready
it becomes obsolete or will be displayed in the admin console).
