### ISSUE TITLE
"allow: Invalid key: admin" when trying to grant admin access

### ISSUE THREAD

**Issue by aardvarkk** [vsivsi/meteor-job-collection#140]
When I try to grant admin access as stated in the documentation I receive an error stating that "admin" is an invalid key for a validator. Does this have something to do with Meteor adding more granularity to allow/deny such that I must now specify individual update, insert, etc. permissions? If that's the case, I'm assuming the documentation just has to be updated to reflect that fact.

**Comment by aardvarkk** [comment]
I'm actually unable to get allow/deny working in any capacity whatsoever. When I try to allow the "update" function only updates still fail with the message: `update failed: Access denied. No allow validators set on restricted collection for method 'update'. undefined`. I definitely have the validator set up to run, it's like it's not being found at all. And when I set it up for admin it says it can't recognize the key. Very strange!

**Comment by vsivsi** [comment]
Hi, this is really basic functionality that is covered by a passing unit test here:  https://github.com/vsivsi/meteor-job-collection/blob/master/test/job_collection_tests.coffee#L61-L65

I just rechecked on Meteor 1.2.1 and everything seems fine.  If you can create a simple reproducing Meteor app, I'll be happy to take a look at your code.

**Comment by vsivsi** [comment]
Hi, this is really basic functionality that is covered by a passing unit test here:  https://github.com/vsivsi/meteor-job-collection/blob/master/test/job_collection_tests.coffee#L61-L65

I just rechecked on Meteor 1.2.1 and everything seems fine.  If you can create a simple reproducing Meteor app, I'll be happy to take a look at your code.

**Comment by aardvarkk** [comment]
I think my problem is that I had placed the code into a file compiled on both the server and client where the command is server-only. I glanced at the "allow" syntax and assumed it would work similarly to the normal allow/deny for collections (which executes on both client and server), but that's not the case. The documentation does specify "Server Only", so I don't think anything necessarily needs to change. It's just a bit tempting to treat it like the normal allow/deny calls and you're not allowed to do that.

**Comment by vsivsi** [comment]
Okay, thanks for reporting back.  That's good feedback, I'm going to leave this open with a documentation tag to remind myself to highlight this in the intro material before the next release.

**Comment by vsivsi** [comment]
Better yet.... when `jc.allow()` or `jc.deny()` are invoked on the client, a warning should be generated or at least the behavior should be benign...

**Comment by vsivsi** [comment]
According to the Meteor 1.2.x docs, `collection.allow()` and `collection.deny()` are server-only.  See: http://docs.meteor.com/#/full/allow
http://docs.meteor.com/#/full/deny

So I'm just going to add warnings if calls to these are attempted on the client.

**Comment by vsivsi** [comment]
Fixed in 1.3.0, will be on Atmosphere today.

**Comment by agnivade** [comment]
Hi,

I seem to have a problem where I am unable to remove jobs from the collection. Saving and finding jobs are working fine. 

My permissions are like this
```javascript
myJobs.allow({
  // Grant full permission to any user
  admin: function (userId, method, params) {
    return true;
  },
  jobSave: function (userId, method, params) {
    return true;
  }
});
```

And this is what I am trying to do at client side -
```
myJobs.remove({_id: "yhSc4PzRbKD3suStp"})
0
remove failed: Access denied. No allow validators set on restricted collection for method 'remove'.
```

Any idea what could be wrong here ? My job-collection version is 1.3.3.

**Comment by vsivsi** [comment]
Hi @agnivade.  Two suggestions:

1) Please open this up as a new issue so we don't spam the participants of this old issue with messages related only to your issue.

2) In order to proceed, I will need to to create a repo on github with a complete working **minimal** Meteor app that demonstrates the issue you are having, including detailed instructions in the README fo reproduce the issue.

Thanks!

**Comment by agnivade** [comment]
Will do. Thanks.
