### ISSUE TITLE
error tried everything - pls help

### ISSUE THREAD

**Issue by vivekmago** [vsivsi/meteor-job-collection#143]
I am a noob trying to use the job collection and have tried everything but unable to get rid of errors below (not sure if my understanding is perfect or somethig else). Any help appreciated

1) Trying to save a job like so
var myJobs =  JobCollection('urlprocesor');
myJobs.setLogStream(process.stdout);

if (Meteor.isServer)
{
  Meteor.startup(function () {
    // Start the myJobs queue running
    myJobs.startJobServer({},function(){
      console.log('server started');
    job = new Job(myJobs,'sendEmail',{some:'data'});
    job.save();
    }); 
  });  
}

Error: 
I20160104-15:43:53.471(-5)? Exception in setTimeout callback: Error: Match error: Failed Match.Where validation in field retries
I20160104-15:43:53.471(-5)?     at check (packages/check/match.js:33:1)
I20160104-15:43:53.471(-5)?     at JobCollectionBase._DDPMethod_jobSave (packages/vsivsi_job-collection/packages/vsivsi_job-collection.js:2515:1)
I20160104-15:43:53.471(-5)?     at JobCollection.<anonymous> (packages/vsivsi_job-collection/packages/vsivsi_job-collection.js:3220:1)
I20160104-15:43:53.471(-5)?     at packages/vsivsi_job-collection/packages/vsivsi_job-collection.js:3128:1
I20160104-15:43:53.471(-5)?     at methodCall (packages/vsivsi_job-collection/packages/vsivsi_job-collection.js:36:1)
I20160104-15:43:53.472(-5)?     at Job.save (packages/vsivsi_job-collection/packages/vsivsi_job-collection.js:1135:1)
I20160104-15:43:53.472(-5)?     at server/jobserver.js:10:1
I20160104-15:43:53.472(-5)?     at packages/vsivsi_job-collection/packages/vsivsi_job-collection.js:32:1
I20160104-15:43:53.472(-5)?     at packages/vsivsi_job-collection/packages/vsivsi_job-collection.js:3125:1
I20160104-15:43:53.472(-5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)

2) Trying to create a job using process Jobs (for same collection as above)

  var workerQueue = myJobs.processJobs('cl',   {
    concurrency: 4,
    payload: 1,
    pollInterval: 5000,
    prefetch: 1
  },
  function(job,cb)
  {
        job.done();
        cb();
  });

Error
W20160104-15:47:13.100(-5)? (STDERR) JobQueue: Received error from getWork():  { [Error: Match error: Failed Match.OneOf or Match.Optional validation]
W20160104-15:47:13.100(-5)? (STDERR)   message: 'Match error: Failed Match.OneOf or Match.Optional validation',
W20160104-15:47:13.100(-5)? (STDERR)   path: '',
W20160104-15:47:13.100(-5)? (STDERR)   sanitizedError: 
W20160104-15:47:13.101(-5)? (STDERR)    { [Error: Match failed [400]]
W20160104-15:47:13.101(-5)? (STDERR)      error: 400,
W20160104-15:47:13.101(-5)? (STDERR)      reason: 'Match failed',
W20160104-15:47:13.101(-5)? (STDERR)      details: undefined,
W20160104-15:47:13.102(-5)? (STDERR)      message: 'Match failed [400]',
W20160104-15:47:13.102(-5)? (STDERR)      errorType: 'Meteor.Error' },
W20160104-15:47:13.102(-5)? (STDERR)   errorType: 'Match.Error' }

**Comment by vsivsi** [comment]
I recommend that you start with one of the working sample apps:
https://github.com/vsivsi/meteor-job-collection-playground
https://github.com/vsivsi/meteor-file-job-sample-app
