### ISSUE TITLE
Links in the table of content (TOC) are broken - 404 error

### ISSUE THREAD

**Issue by a4xrbj1** [vsivsi/meteor-job-collection#146]
Error in the otherwise excellent documentation.

They lead nowhere, eg https://github.com/vsivsi/meteor-job-collection/blob/master/#user-content-logging which is used in every link of the TOC

**Comment by vsivsi** [comment]
Hi, I'm not seeing this problem.

If you access the README from the repo home page:
https://github.com/vsivsi/meteor-job-collection
Then the links work and are of the form:
https://github.com/vsivsi/meteor-job-collection#user-content-use

If you access the README file directly:
https://github.com/vsivsi/meteor-job-collection/blob/master/README.md
Then the links still work, but then refer to the master branch blob:
https://github.com/vsivsi/meteor-job-collection/blob/master/README.md#user-content-use

Other branches work too:
https://github.com/vsivsi/meteor-job-collection/blob/dev/README.md#user-content-use

The link you provided above looks like a hybrid of the repo homepage and the master branch URLs.  Where did that come from?

**Comment by vsivsi** [comment]
Oh I see, those are the links on Atmosphere.  That seems like an Atmosphere bug.  The Markdown source for those links are simply relative anchor links:

```md
## Table of Contents

- [Quick example](#user-content-quick-example)
- [Design](#user-content-design)
- [Installation](#user-content-installation)
- [Use](#user-content-use)
  - [Security](#user-content-security)
  - [Performance](#user-content-performance)
  - [Removing Old Jobs](#user-content-removing-old-jobs)
  - [Logging](#user-content-logging)
- [JobCollection API](#user-content-jobcollection-api)
- [Job API](#user-content-job-api)
- [JobQueue API](#user-content-jobqueue-api)
- [Job document data models](#user-content-job-document-data-models)
- [DDP Method reference](#user-content-ddp-method-reference)
```

Github.com seems to do the right thing in every case, but Atmosphere is translating them into broken links to Github, rather than linking within the page on Atmosphere itself.  A TOC that links to an external page seems way less useful to me!

**Comment by a4xrbj1** [comment]
You might want to take the "can't reproduce" away ;-)
