### ISSUE TITLE
Is there any alternative to logging job output?

### ISSUE THREAD

**Issue by a4xrbj1** [vsivsi/meteor-job-collection#147]
Hi Vaughn,

I checked this issue: https://github.com/vsivsi/meteor-job-collection/issues/21 but I don't understand the solution. I want to avoid clogging up my console on development with the standard:

    // Log everything to stdout
    myJobs.setLogStream(process.stdout);

and instead would like to write it to a local file.

Also, how are others running the log on the production apps? The output of the job worker is important to find errors, especially in production.

Apart from this professional solution (https://www.loggly.com), what are people using?

**Comment by rhyslbw** [comment]
@a4xrbj1 I recently added [additional documentation to the section on logging](https://github.com/vsivsi/meteor-job-collection#user-content-logging) highlighting the use of the job-collection `call` event to generate custom logs. I'd suggest using [Winston](https://github.com/winstonjs/winston) as your logger, which is highly configurable and comes with built-in [transports](https://github.com/winstonjs/winston/blob/master/docs/transports.md), including [file](https://github.com/winstonjs/winston/blob/master/docs/transports.md#file-transport), and optional add-on transports suited for production. I like to use [Papertrail](https://papertrailapp.com/), which has a [transport](https://github.com/kenperkins/winston-papertrail) that's not listed on that page.

This is an example of how we [implemented this in Space](https://github.com/meteor-space/base/blob/develop/source/logger.js), currently only a console logger.

**Comment by a4xrbj1** [comment]
Thanks @rhyslbw for your suggestions. I briefly looked into them and consider them good solutions once I go into production (not even in beta yet).

For the moment I would be happy if I could stop seeing those ten thousands (literally, just run 30000 jobs in 1h 20m) `Job Y9dbC3kndcff7mKTF finished!` messages. I haven't checked the documentation, maybe there is a way to surpress them.

**Comment by rhyslbw** [comment]
You can easily get access to the same data by subscribing the the `call` event, then remove `myJobs.setLogStream(process.stdout)`. I just did a quick search on Atmosphere, and it looks like this should be a simple way to dump the logs to a file https://atmospherejs.com/ostrio/loggerfile
