### ISSUE TITLE
Should be "promote" named "beat"

### ISSUE THREAD

**Issue by mitar** [vsivsi/meteor-job-collection#15]
Just asking, because this is something used in [Celery](http://celery.readthedocs.org/en/latest/userguide/periodic-tasks.html)?

And should be clearer that you want/need only one process doing those checks/queries?

**Comment by rhyslbw** [comment]
@mitar 
> If all instances start at the same time, how does one make sure there is reasonable delay between them promoting so that it is not that all run at the same time, but N * milliseconds apart.

I guess this should be handled by the cluster's manager. How are you staggering the `promote` calls across multiple instances?

**Comment by mitar** [comment]
I made all this mine logic into [this package](https://github.com/peerlibrary/meteor-classy-job).

**Comment by mitar** [comment]
See the [worker file](https://github.com/peerlibrary/meteor-classy-job/blob/master/worker.coffee).

**Comment by rhyslbw** [comment]
thanks for the link @mitar. How are you managing the cluster of instances? Just curious to know what your deployment approach is, and how you're setting the ENV to control the promote interval.

> jobs ought to be idempotent
+100 btw

@vsivsi it's great to see dependents of job-collection, and how the APIs are being used. Would you be open to a section in the Readme for a list of projects like this? I'm working on a [module for Space](https://github.com/meteor-space/job-queue), so there will be at least two for that list :-)

**Comment by mitar** [comment]
You see in the [README](https://github.com/peerlibrary/meteor-classy-job#initialization). The package allows you to pass the number of worker instances to the constructor, and by default it reads `WORKER_INSTANCES` environment variable. Here is how I [initialize it](https://github.com/mitar/council-app/blob/master/packages/core/worker.coffee).

**Comment by rhyslbw** [comment]
Yes I understand, just trying to assess if this design would work if scaling the cluster in production. Guess you can just use the ENV to init, then live update the running instances via DDP . thanks again

**Comment by mitar** [comment]
In production I use rolling update to restart instances anyway. So a new configuration for Docker instances go so that I first over provision with new configuration and then remove those with old configuration.

**Comment by mitar** [comment]
At some point I will have to [externalize](https://github.com/peerlibrary/meteor-peerdb/blob/master/server.coffee#L36) my messaging service I use for inter-instance communication in PeerDB. It would be a great tool to have it communicate across instances for now just PeerDB.

**Comment by rhyslbw** [comment]
Got it, cheers. Yer no need to prematurely optimise

**Comment by vsivsi** [comment]
> it's great to see dependents of job-collection, and how the APIs are being used. Would you be open to a section in the Readme for a list of projects like this? I'm working on a module for Space, so there will be at least two for that list :-) 

@rhyslbw  Yes!  PR away!
