### ISSUE TITLE
How to pause all jobs and stop (cancel) all running jobs?

### ISSUE THREAD

**Issue by a4xrbj1** [vsivsi/meteor-job-collection#154]
Another tricky question. I'm experiencing a phase where the server that I'm querying with http calls via job workers is giving me a 503 error (Service unavailable). I'd like to put all current (including running) jobs on hold.

This is what I'm doing:

**Step 1:** First of all, instead of executing `processJobs` like this:

`jc.processJobs();`

I have to use:

`queue = jc.processJobs();`

to have a job queue in the first place that I can pause.

The complete code is this:

```
queue = jc.processJobs( 'jobName', { workTimeout: 5000 }, function (job, cb) {
    doSomething(function(err) {
        if (err) {
            job.fail("" + err);
        } else {
            job.done();
        }
        cb();
    });
});
```

Then I need to execute:

`queue.pause();`

which should put all jobs in that queue (as there are thousands, if not ten thousands in my case) on hold. But no status change seems to happen. I do have 16 jobs with the status of `waiting` and 8 jobs with the status of `ready`. After executing the above line it's still the same, no job is now `paused`. According to the documentation under `jc.jobStatusPausable` both `waiting` and `ready` should change to `pause`.

What am I doing wrong here?

**Step 2:** Running jobs need to be canceled:

As I started many jobs, I first need to identify which jobs have the status of running:

```
var res = myJobs.find({ status: {$eq: "running"} });
res.forEach(function(doc) {
    // now cancel every running job
    console.log('Job id: ' + doc._id);
    doc.cancel({}, function (err, result) {
        if (result) {
            count++;
        }
    })
});
console.log(count + ' Jobs cancelled');
```

But I get the following error message:

`TypeError: Object #<Object> has no method 'cancel'`

when I execute the `doc.cancel()`line. How can I get a `job object`?

**Comment by vsivsi** [comment]
`queue.pause()` will only pause that one worker's local queue from accepting any more work from the server (it does not change the status of jobs on the server).  If you want to pause all such jobs in server's JobCollection, then you need to run [`jc.pauseJobs(...)`](https://github.com/vsivsi/meteor-job-collection#jcpausejobsids-options-callback---anywhere).  That takes a list of `_id` values (there is no "all" option), so you'll need to couple it with a lookup...  You can see code that does this in the playground app here:  https://github.com/vsivsi/meteor-job-collection-playground/blob/master/play.coffee#L337-L338

There's a bit of a chance of a race condition in that approach (it won't pause jobs created between the find and the pause), and if that's a problem for you, you can implement a server-side method that does an update to the `status` of all `{ status: { $in: Job.jobStatusPausable }}` jobs directly.

The second problem is that `res` is just a document, not a Job object.  You can either just make it into one: `job = new Job(res)` or you can add a transform rule to do that automatically: https://github.com/vsivsi/meteor-file-job-sample-app/blob/master/sample.coffee#L19-L24

**Comment by a4xrbj1** [comment]
I've tried to identify pausable jobs given your above query through the console but I've got the following error message: `ReferenceError: Job is not defined` when running `db.myJobQueue.jobs.find({ status: { $in: Job.jobStatusPausable }})`

I've tried the following two commands `db.myJobQueue.jobs.find({ status: { $in: myJobQueue.jobStatusPausable }})` and `db.myJobQueue.jobs.find({ status: { $in: jobs.jobStatusPausable }})` with the same error message. I don't know what to use instead of `Job`

**Comment by vsivsi** [comment]
jobStatusPausable Is a property of the job collection. See:
https://github.com/vsivsi/meteor-job-collection#jcjobstatuspausable---anywhere

Is it just a convenience alias: `jc.jobStatusPausable = [ 'ready', 'waiting' ];
`
