### ISSUE TITLE
Job.Depends as Wait On

### ISSUE THREAD

**Issue by Chugot** [vsivsi/meteor-job-collection#159]
Hello Sir,

I am using jobCollection to run a variety of batch jobs, some of which have user provided parameters and some that can take quite a while.  Basically I am trying to check for a job of the same type running already, and if it is, to hold off on execution of the next instance of that job until the previous one is complete.  The catch here is that I do not necessarily care whether the previous job failed or succeeded as to whether the next instance should begin trying to execute.  

A use case would be that the job has a server parameter, so they queue up two instance of the job for different servers, and  because of some shared local resources I do not want them running simultaneously.  If the first job fails because the server is not available, I still want it to run the next instance of the job.

Is this possible as is with jobCollection or do I need to create logic separately to determine whether the previous job of the same type has completed?   I currently have it checking for a running job and if so attaching it as a dependency, but according to the docs that will only help me if the previous job succeeds.  It has been a long day so if I am missing something already there please forgive me :).

Any help you can provide will be much appreciated!

**Comment by vsivsi** [comment]
Hi, perhaps I am over-simplifying the problem you are describing, but if you only have one worker instance and limit its concurrency (and payload) to `1`, then by definition only one job at time of that type can be running. Of course, these are the defaults... So, unless you are creating multiple worker processes for this job type, something like the code below should suffice. 

```js
jq = jc.processJobs(
     'oneAtATimeJob',
     { 'concurrency' : 1, 'payload' : 1 },  // defaults
     function (job, callback) {
          // Only one job at a time can be in here...
          job.done();
          callback();
     }
);
```

If for some reason you would like to have multiple workers, but serialize their access to a shared resource, then some type of external locking will be necessary. In this case, you might find this npm package useful: https://www.npmjs.com/package/gridfs-locks

It can only run on the server (e.g. the [vsivsi:file-collection](https://github.com/vsivsi/meteor-file-collection) package uses it), but you could (for example) wrap calls to it in Meteor.methods to enable workers to remotely lock/unlock access to shared resources.

**Comment by Chugot** [comment]
I had thought about limiting the payload at the worker, unfortunately I have 300+ batch jobs that can be run and am currently using only 2 workers to run them (local or remote).  Sounds like it is not going to be natively available the way I'd like it but that's not a problem, I can just move the wait logic into an interval and check for completion before I submit the job.  Thanks for the follow up anyways and for the package suggestion!
