### ISSUE TITLE
"Match error: Expected string, got object"

### ISSUE THREAD

**Issue by JohnAllen** [vsivsi/meteor-job-collection#16]
We got the error above with the stack trace in the image.

![screen shot 2014-07-15 at 6 14 36 pm](https://cloud.githubusercontent.com/assets/2800641/3593482/3622d38c-0c87-11e4-9c81-58b7891ff597.png)

The code is essentially structured to the code in issue #9.

This only happens using node-inspector BTW.

Any thoughts?

**Comment by vsivsi** [comment]
Resolved long ago.  Closing.
