### ISSUE TITLE
Set retries to 0 of a running job with a schedule

### ISSUE THREAD

**Issue by dcusan** [vsivsi/meteor-job-collection#161]
Hi @vsivsi,

this package is a absolute lifesaver in the Meteor world, love it!

However I'm trying to accomplish the following and I am not having much luck. I guess this is more of a question rather than a bug.

As I mentioned in the description I have the following scheduled job:
```javascript
const schedule = Jobs.later.parse.text('every 5 seconds');
job.repeat({schedule: schedule}).retry({retries: 3, wait: 5000}).save();
```

I'm running the whole worker code in a `try ... catch` statement, which if 'catched' I want to be retried up to 3 times as described.

However there is one circumstance in which I want the running job to be immediately failed and not be retried, so that within an `if` statement of the worker code I have the following code:

```javascript
job.retry({retries: 0}).fail('Woops, no retries here please');
return cb();
```

Unfortunately the original retries still prevail and the jobs reruns up to 3 times before actually failing.

Is there a way of achieving this? I also thought of modifiying the job document directly, but I don't know if it is such a good idea. Can you advise on this?

If helpful, I can upload some example code to a repo.

Thank you!

**Comment by vsivsi** [comment]
You should look at the `fatal` option to `job.fail()`. Does exactly what you need, no messing around with retry counts, etc.   https://github.com/vsivsi/meteor-job-collection#jobfailerror-options-callback---anywhere

**Comment by vsivsi** [comment]
One other bit of advice given your description... Make sure that you catch any errors that can be thrown within your `catch` clause, or control will leave the worker function without invoking the callback, which will freeze up that worker from taking future jobs.  See: https://github.com/vsivsi/meteor-job-collection/issues/158

**Comment by dcusan** [comment]
Exactly what the doctor ordered, can't believe I missed that. I looked at the docs real close (not close enough I guess).

Thanks for the advice too, exactly that happened while testing this out and I made sure I catch everything.

Thanks again, also for the prompt response!
