### ISSUE TITLE
looped jc.getJob() != jc.getJobs()

### ISSUE THREAD

**Issue by Szayet** [vsivsi/meteor-job-collection#163]
Looping **jc.getJob** return the job's with their document `_id`s included whereas **jc.getJobs** does not conclude `_id` field in the returned job's documents.

The following code, (if `jobs` declared by **getJobs**) wont work because of the following error: `Error: Each provided object must be a saved Job instance (with an _id)` 
Meanwhile looping **getJob** get's the job done. ;)

``` js
while(jobs.length > 1) {
      var currentJob = jobs.shift();
      currentJob.pause();
      currentJob.depends(jobs).save();
}
```

**Comment by vsivsi** [comment]
I just wrote a unit test for this and I can't reproduce the behavior you describe...  

https://github.com/vsivsi/meteor-job-collection/commit/6945167fed13e0af6a4600ef9eea4c416a6a63f3
