### ISSUE TITLE
How to delayed re-queue a job by a worker?

### ISSUE THREAD

**Issue by bluepuma77** [vsivsi/meteor-job-collection#169]
Is it possible that my worker can re-queue a job that is delayed for a time before re-processing.

The [extensive chart](https://raw.githubusercontent.com/vsivsi/meteor-job/master/doc/states.dot.cairo.png) is great, I tried delay, retry, cancel, restart - but that didn't work for me.

What's best practice to re-run a job a bit later (when worker still needs to wait for dependencies)?

**Comment by vsivsi** [comment]
Hi, It really depends on what you are trying to do...

One possibility is to set the job to retry `forever`, and just fail each time until the dependency is met...
https://github.com/vsivsi/meteor-job-collection#jobretryoptions---anywhere

If the dependency is actually coming from another job, then you can make one job depend on the other...
https://github.com/vsivsi/meteor-job-collection#jobdependsdependencies---anywhere

Which way to do it really depends on the nature of the dependency and how your code is informed of its readiness (polling, observe callback, an event, another jobs, etc.) If polling, then the retry/fail pattern above is probably best. If its another job, use dependencies. If its a callback (event or observe) then it's probably best to just delay scheduling the job at all until everything is ready (you can create it, but delay saving it; or you can save it in a paused state, and resume it when the event is satisfied...) 

Hope that helps.

**Comment by bluepuma77** [comment]
Thanks for the detailed response!
