### ISSUE TITLE
What might cause "Running job not found"?

### ISSUE THREAD

**Issue by dandv** [vsivsi/meteor-job-collection#17]
Here's the error:

```
Run status: Running...
Ready fired: 0 jobs promoted
(STDERR) Running job not found { _str: '6554921095bc0437e43698f6' } { _str: 'b5bbe0304779b27ee5686da1' }
Jobs in queue: 1
Exception in setTimeout callback: TypeError: Cannot read property 'name' of undefined
    at JobQueue.worker (app/server/articles.js:69:70)
    at JobQueue._process (packages/jobCollection/job/src/job_class.coffee:154:7)
    at _.extend.withValue (packages/meteor/dynamics_nodejs.js:37)
    at packages/meteor/timers.js:6
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:89)
Run status: Running...
Ready fired: 0 jobs promoted
```

And the code:

```js
var queue;
queue = SB.feedParsingJobs.processJobs(
  'parseFeed',
  {
    concurrency: 1,
    cargo: 1,
    pollInterval: 5000,
    prefetch: 1
  },
  function (job, callback) {
    var feed = job.data.feed, newsSource = SB.NewsSources.findOne(job.data.newsSourceId);
    console.info('--- Processing feed', feed.title, '|', newsSource.name);  // <-- app/server/articles.js:69:70)
    ...
```

This is on MongoDB 2.6. Haven't seen the behavior on 2.4.3, but there might be other variables that differ between the deployments and might affect this.

**Comment by vsivsi** [comment]
@mitar  I don't think it is.  This question had to do with a different kind of failure: when a running job has been cancelled/failed/restarted and the original worker doesn't know it yet.

@dandv  I'm going to close this issue unless you have some remaining questions about the case you describe above (it's been so long, I can't imagine you do...)

**Comment by dandv** [comment]
@vsivsi: sorry, I haven't used the package in a while. Let me close...

**Comment by a4xrbj1** [comment]
I just run into the same problem as the query took 17 seconds to finish and I unfortunately set the timeout way too low. After I increased it to 60000ms the job run without any problems.

Many thanks for building such a function (the reaper I mean)!
