### ISSUE TITLE
How to easily check if jobServer is running?

### ISSUE THREAD

**Issue by luixal** [vsivsi/meteor-job-collection#187]
This is, there are functions to start and shutdown the server, and there's a function for checking if a queue is running... is there any function to check whether the job server is running or not?

Or do you have to check your queues or keep an status variable on your own?

Thanks!

**Comment by vsivsi** [comment]
On the server you can check `jc.stopped`.  If you want access to that on a client, you can write a meteor method to return that value, or write a custom publish function if you want it to be reactive on the client  (triggered by events emitted for `startJobServer` and `shutdownJobServer`, see `jc.events`).

**Comment by luixal** [comment]
I finally went with the method solution because no reactivity was needed in this case. Thanks!
