### ISSUE TITLE
Why getWork limits jobs based on time

### ISSUE THREAD

**Issue by mitar** [vsivsi/meteor-job-collection#19]
I am reading code and I see that [getWork query](https://github.com/vsivsi/meteor-job-collection/blob/master/shared.coffee#L243) has:

```
        after:
          $lte: time
```

Why? Isn't it so that job can have a state "ready" only when promote determined that it is ready to run and set state to "ready"? How could it be that it would have state "ready" and still have after later than current time?

I am asking this because I am working on a observe-based worker and as you know one cannot make a query based on current time. I thought that the whole point of having promote is to address this issue. And now I see that query still uses current time?

**Comment by vsivsi** [comment]
This was resolved long ago.
