### ISSUE TITLE
how to update or insert in collections from workers

### ISSUE THREAD

**Issue by iBet7o** [vsivsi/meteor-job-collection#191]
Hi o/!

I've a file with workers outside meteor develop. How you could access collections from workers?

try to call the method with `ddp.call` but not if it is correct.

regards

**Comment by vsivsi** [comment]
Hi, this is really a question for the [node DDP client package](https://github.com/oortcloud/node-ddp-client).  You should be able to subscribe to published document sets and call server-side methods to modify collection documents using that package.

**Comment by iBet7o** [comment]
ok, thanks @vsivsi
