### ISSUE TITLE
getWork is too strict on what document it gets from the database

### ISSUE THREAD

**Issue by mitar** [vsivsi/meteor-job-collection#20]
I am adding some extra fields to Job collection documents, and I am also using Meteor transform to get documents wrapped with some helper methods (I have this for all my documents in all Meteor collections). Because of this this [check fails](https://github.com/vsivsi/meteor-job-collection/blob/master/shared.coffee#L303). Why it is there? I think this is a bit over checking. Checking if database is returning data. Yes, it is. :-)

**Comment by vsivsi** [comment]
Closing this. Everything in here is done.
