### ISSUE TITLE
Run a recurring job now

### ISSUE THREAD

**Issue by Skulmuk** [vsivsi/meteor-job-collection#220]
I have a job that runs every 10 minutes. If I want to override a single instance of it and run it now (i.e. via a button press), how should I do it? I figured the following should work, but to no avail:

```javascript
    const job = Jobs.findOne({ 'data.name': name, status: 'waiting' });
    if (job) {
      const j = Jobs.getJob(job._id);
      j.ready({ time: new Date(), force: true });
    }
```

**Comment by vsivsi** [comment]
The playground app implements exactly the functionality you describe. 

https://github.com/vsivsi/meteor-job-collection-playground/blob/master/play.coffee#L187

**Comment by Skulmuk** [comment]
Thanks, @vsivsi - that works a treat :)
