### ISSUE TITLE
Broken with Meteor 1.5

### ISSUE THREAD

**Issue by ujwal-setlur** [vsivsi/meteor-job-collection#237]
I updated my meteor 1.4 project to 1.5, and job-collection seems broken:

```
W20170602-09:49:38.449(-7)? (STDERR) Error: JobQueue: Invalid root, must be nonempty string
W20170602-09:49:38.452(-7)? (STDERR)     at new JobQueue (packages/vsivsi_job-collection/job/src/job_class.coffee:114:17)
W20170602-09:49:38.454(-7)? (STDERR)     at job/src/job_class.coffee.js:175:45
W20170602-09:49:38.454(-7)? (STDERR)     at Function.JobQueue [as processJobs] (packages/vsivsi_job-collection/job/src/job_class.coffee:110:18)
W20170602-09:49:38.455(-7)? (STDERR)     at meteorInstall.imports.startup.server.startup-cron-jobs.js (imports/startup/server/startup-cron-jobs.js:25:5)
W20170602-09:49:38.456(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170602-09:49:38.457(-7)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170602-09:49:38.459(-7)? (STDERR)     at meteorInstall.imports.startup.server.index.js (imports/startup/server/index.js:1:201)
W20170602-09:49:38.463(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170602-09:49:38.468(-7)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170602-09:49:38.471(-7)? (STDERR)     at meteorInstall.server.main.js (server/main.js:1:14)
W20170602-09:49:38.475(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170602-09:49:38.476(-7)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170602-09:49:38.476(-7)? (STDERR)     at /Users/ujwal/Work/grubmobile/gm-server/.meteor/local/build/programs/server/app/app.js:5809:1
W20170602-09:49:38.477(-7)? (STDERR)     at /Users/ujwal/Work/grubmobile/gm-server/.meteor/local/build/programs/server/boot.js:338:34
W20170602-09:49:38.477(-7)? (STDERR)     at Array.forEach (native)
W20170602-09:49:38.479(-7)? (STDERR)     at Function._.each._.forEach (/Users/ujwal/.meteor/packages/meteor-tool/.1.5.0.ptpcut++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
=> Exited with code: 1
```

**Comment by vsivsi** [comment]
I'm away on a trip and won't be able to look into this until mid-June.

**Comment by ujwal-setlur** [comment]
Any updates on this? I could look into this if I had a pointer on where to start. Thanks!

**Comment by vsivsi** [comment]
I just upgraded the [playground app]() from Meteor 1.4.2.3 to Meteor 1.5 without any issues. This seems like an issue that is specific to your app/code, which I obviously don't have access to.

**Comment by ujwal-setlur** [comment]
OK, I will look more into it and send you a code snippet of how I am using the package.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vsivsi** [comment]
I really need a full **minimal** reproduction app to proceed in helping with any debugging like this.  Just dropping a code snippet on me to review will not be a good use of either of our time, I need running code and instructions that clearly reproduce the issue with a minimum of effort on my part. Sorry to be such a stickler, but I've wasted untold hours trying to remotely debug other people's code only to have it be something that had nothing to do with my code.

**Comment by ujwal-setlur** [comment]
Yes, no worries. I am used to receiving and analyzing bug reports as well. I will put up a skeleton app.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ujwal-setlur** [comment]
I resolved the issue by replacing ```Job.processJobs()``` with ```jc.processJobs()```. Thanks for looking into this. This was an application code error. Apologies!

**Comment by vsivsi** [comment]
No worries, glad you figured it out!
