### ISSUE TITLE
Question: how to prevent creating Meteor methods

### ISSUE THREAD

**Issue by mitar** [vsivsi/meteor-job-collection#24]
I am not planing to use Meteor methods provided to the client, because I have my own methods to do actions, which I plan for them to create jobs on the server side. I thought that I could simply keep deny rules in place and leave methods be, but then I cannot really call any method on the server side from server side methods, even if I verified for permissions on my own in my own methods. So, how:
* I disable creating Meteor methods (and then I can 'allow all" for calling, because methods can be called from the server only anyway)
* I can call methods from other methods, without having to open permissions to clients

**Comment by vsivsi** [comment]
This is fixed in master branch.
