### ISSUE TITLE
Running a heavy load job right now on the next available server

### ISSUE THREAD

**Issue by kellertobias** [vsivsi/meteor-job-collection#242]
I have some jobs that needs to be done soon (actually the jobs is scheduling of future jobs as described here: https://forums.meteor.com/t/best-way-to-run-processing-heavy-task-inside-of-meteor/30629/12)

is it possible to do this with your package?

**Comment by vsivsi** [comment]
Yes. I suggest you read the documentation and examine the sample apps it links to.
