### ISSUE TITLE
Echoing should go to log stream not console.log

### ISSUE THREAD

**Issue by mitar** [vsivsi/meteor-job-collection#26]
Currently `log` and `progress` can echo things. But they go to `console.log` and not to log stream? I think this should be configurable.

**Comment by vsivsi** [comment]
I'm closing this one. I think echo is fine as it is.

**Comment by mitar** [comment]
Can you just make a function you call? `_debug`? So that it can be overridden?

**Comment by vsivsi** [comment]
I'll look at it again...

**Comment by vsivsi** [comment]
How about this: https://github.com/vsivsi/meteor-job/blob/dev/src/job_class.coffee#L470

**Comment by mitar** [comment]
Perfect! Thank you!

**Comment by vsivsi** [comment]
Great!
