### ISSUE TITLE
Code is too noisy

### ISSUE THREAD

**Issue by mitar** [vsivsi/meteor-job-collection#28]
Code has all around `console.log` end outputs it even when things work. I thing this should really be consolidated. So debug statements are OK, but there should be a way to disable that. Logging is good, but it should be clear what are info messages and what are errors. For workers you have that for echo mode, but for server you do not. And code has all around things like `console.log "jobFail succeeded"`.

Noisy logs mean that it is hard to see errors. I would create four logs (debug, info, warning, error) and then all prints pass through that. And then it should be possible to extend this logging in various ways (for streams, `logging` package, sending to centralized server, etc.).

**Comment by DenisGorbachev** [comment]
:+1:

**Comment by vsivsi** [comment]
This is definitely on my radar.  Stay tuned.

**Comment by vsivsi** [comment]
Just committed to master. Will be in next release

**Comment by brentjanderson** [comment]
Is this intended to be here still? This console.log generates a lot of messages when calling job.progress frequently.

https://github.com/vsivsi/meteor-job-collection/blob/master/shared.coffee#L769
