### ISSUE TITLE
Unclear documentation about cancelRepeats

### ISSUE THREAD

**Issue by mitar** [vsivsi/meteor-job-collection#29]
In `repeat` documentation it seems like `cancelRepeats` is set to true by default for all forever repeatable jobs:

> By default, if an infinitely repeating job is added to the job Collection, any existing repeating jobs of the same type that are cancellable, will be cancelled.

But from code this is not true. It seems that `cancelRepeats` is false by default and only if set to true and the job is forever repeatable, old jobs will be cancelled.

**Comment by vsivsi** [comment]
Fixed in dev branch

**Comment by vsivsi** [comment]
Merged with master, closing
