### ISSUE TITLE
TODO list for v1.0 release

### ISSUE THREAD

**Issue by vsivsi** [vsivsi/meteor-job-collection#31]
@mitar  I've created a branch called `v0.1.0_RC`.  I'm busy for the rest of the week and can't work on this project any more until Monday. 

You can help me out by collecting what you see as all of the outstanding issues and making a list of them on this issue.  There are too many threads of conversation going and if you can help organize it all for me here, that will help me get a quick start on Monday when I can turn my attention back to this project. 
 
Also, if you'd like to press forward and make some changes yourself in the meantime, please fork from `v0.1.0_RC` and I'll consider and PRs on Monday.

**Comment by vsivsi** [comment]
_validJobDoc is now available as `jc.jobDocPattern` see:  https://github.com/vsivsi/meteor-job-collection/tree/dev#jcjobdocpattern---anywhere

**Comment by vsivsi** [comment]
One checkbox to go!  But I need to sleep, so it waits until tomorrow...

**Comment by rhyslbw** [comment]
Nice work, but should this not be the packages' 1.0 release considering the API will be dependable and the initial development phase complete?

 [Semver outlines](http://semver.org/)
>Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

>Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.

**Comment by vsivsi** [comment]
@rhyslbw  Yes, 1.x is my intent for the upcoming release.  The title of this issue is old.

**Comment by vsivsi** [comment]
Also, to reflect this, all development has moved to a branch called `dev`

**Comment by rhyslbw** [comment]
:+1:

**Comment by vsivsi** [comment]
The first issue on this list doesn't seem to be an issue.  see: https://github.com/vsivsi/meteor-job-collection/issues/30#issuecomment-73612870

I'll wait to hear back from @mitar on that, but I think I'm done here.

**Comment by mitar** [comment]
This is amazing. :-) Do you think [logging should be silenced and extension point made](https://github.com/vsivsi/meteor-job-collection/issues/23#issuecomment-73613784) before 1.0 release?

**Comment by vsivsi** [comment]
I'm looking at that now.

**Comment by rhyslbw** [comment]
For consideration: https://github.com/vsivsi/meteor-job-collection/issues/8

**Comment by leebenson** [comment]
@vsivsi, do you have an ETA for pushing the v1 release? I'm about to deploy this into production for a e-mail queue, and would really love to turn off those console.log messages. Thanks!

**Comment by vsivsi** [comment]
Hi, it should be next week. I've been working on a big update for my other main Meteor package file-collection, and I'm just finishing that up now. I may get some time over the weekend to work on this, but if not, it'll be by Wednesday.  Thanks!

**Comment by vsivsi** [comment]
I just published the 1.0.0 update to file-collection.  Now I'm working on doing the same for job-collection.  Not sure if I'll get it completely finished today, but if not I will be published tomorrow.  Thanks to all for your patience, it feels good to finally get this wrapped up!

**Comment by vsivsi** [comment]
New TODO list:

- [ ] Rename the server control methods: https://github.com/vsivsi/meteor-job-collection/issues/8#issuecomment-74233557

**Comment by leebenson** [comment]
You're awesome, thanks!

**Comment by alexzaporozhets** [comment]
Thank you for your work! Looking forward to the release

**Comment by vsivsi** [comment]
Just to keep everyone informed... I had some higher priority stuff come up last week, but I'm back working on the release again now. 

Most of the remaining work is just testing all of the new features; especially the ability to run workers on one Meteor server against a job collection hosted on another Meteor server (via the new `ddp` option on the server-side constructor: https://github.com/vsivsi/meteor-job-collection/tree/dev#jc--new-jobcollectionname-options---anywhere).  

If you want to help test, the `dev` branch should be stable.  Any and all feedback is welcomed.

**Comment by rhyslbw** [comment]
Is there a breaking change relating to accessing data on the job document?

**Comment by vsivsi** [comment]
Another quick update...  I'm still working on some issues with #59, and I need to do a bunch of testing with Meteor 1.0.4.x that just released today.  

Once we work through these things, the v1.0 release should (at long last) be ready to drop.

**Comment by rhyslbw** [comment]
Pretty sure the only outstanding issue is #67

**Comment by vsivsi** [comment]
FYI, dev branch has been merged with master.  I need to write a bit more documentation and then I'm going to publish v1.0.0 tonight!

**Comment by vsivsi** [comment]
v1.0.0 Released to Atmosphere!  Closing this issue!

**Comment by mitar** [comment]
:-)

**Comment by rhyslbw** [comment]
Great work!

**Comment by petrometro** [comment]
This is a super useful package !
