### ISSUE TITLE
DB architecture: completed repeating jobs vs. running jobs

### ISSUE THREAD

**Issue by dandv** [vsivsi/meteor-job-collection#36]
We have a [fixed number (~70) of infinitely repeating jobs of the same type (feed parsing)](https://github.com/vsivsi/meteor-job-collection/issues/9#issuecomment-47180085). In the database, this creates thousands of `status: completed` jobs, and the fixed number of `running` jobs.

Revisiting jobCollection after a while away from it, I was wondering if it would make more sense to only have the repeating jobs stored in Mongo, and their past completed occurrences stored in an array within each job object, similar to `log`. That would make the array unwieldy to manipulate (and might break Mongo's 16Mb object size limit) though. Is this the reason that the `.jobs` collection contains in fact *invocations* rather than jobs per se?

The difference I see between running jobs and (past) completed job invocations is that running jobs need to contain fields like `data` or `repeats` and `retries`, while completed instances would contain `repeat*ed*` and `retri*ed*`.

Would two collections make sense? Would be interested in your thoughts on this.

**Comment by vsivsi** [comment]
There's enough momentum with the present design that I'm going to leave this as-is.  The solution to cleaning up completed jobs is to write a new type of job that runs on the server and disposes of them in whatever way meets the needs of your specific application (discard, archive in another collection, compile aggregate stats, etc.)
