### ISSUE TITLE
Update to Meteor 0.9.0

### ISSUE THREAD

**Issue by chhib** [vsivsi/meteor-job-collection#39]
Please update to Meteor 0.9.0 packaging system.

Thanks

**Comment by joeapearson** [comment]
@vsivsi we could still use the `meteor_0.8_compat` branch.  I think it's since been removed.  Any ideas which commit we should look at?

**Comment by vsivsi** [comment]
@joeapearson  version 0.0.16 is the last release that supported Meteor 0.8 style packages.
https://github.com/vsivsi/meteor-job-collection/releases/tag/v0.0.16

**Comment by joeapearson** [comment]
@vsivsi belated thanks!
