### ISSUE TITLE
ReferenceError _str is not defined - When using a meteor package in a worker

### ISSUE THREAD

**Issue by gerwinbrunner** [vsivsi/meteor-job-collection#46]
Hi,

I'm trying to access a meteor package in a worker and this seems not to work. 

This is how I call the worker:
```
  workers = JobQueue.processJobs([JobQueue.jobNames.jvcpCheck, JobQueue.jobNames.jvcpImport], { concurrency: 2, cargo:1, prefetch: 0, pollInterval: 3000 }, worker)

```

In the worker I have the following code:
(the same code works in the client, so the package is available in the regular meteor app)
```
 _str.slugify(l.name)
```

When the job is run I get the following error:
```
Job[oShGvpowfxZtJjWuH] ReferenceError _str is not defined
```

The package I'm using is this:
mrt:underscore-string-latest@2.3.3

Any idea what I'm doing wrong here?

Best,
Gerwin

**Comment by vsivsi** [comment]
@gerwinbrunner   Have you solved this issue?   Please let me know so I can close it if solved.

**Comment by vsivsi** [comment]
Closing old issue
