### ISSUE TITLE
Callback when job enters 'failed' state?

### ISSUE THREAD

**Issue by rmbrich** [vsivsi/meteor-job-collection#52]
Hi,
I'd like some code to run when the job enters 'failed' state, i.e. all 5 retries have happened, they have failed, job.fail() has been called 5 times, now the job enters 'failed' state instead of 'waiting'. 

I may be missing something in the documentation, but how can I do this?

Thanks,
R

**Comment by TimFletcher** [comment]
Just incase anyone runs into this, you currently can't use `Method.call` in an observe due to https://github.com/meteor/meteor/issues/907. It's supposed to work if you put the call into a `setTimeout` or `Meteor.defer` but neither worked for me.
