### ISSUE TITLE
Dependent repeating jobs looses depends link

### ISSUE THREAD

**Issue by LarsBuur** [vsivsi/meteor-job-collection#60]
If I have jobX and jobY and let jobY  be dependent on jobX and set jobX to repeat every x minutes then the following happens.

jobX executes and are rescheduled. jobY executes after jobX and when finished changes state to completed and are not rescheduled.

If I "force" jobY to have a repeat interval then jobY is repeated as well and executed after jobX but the dependency between the two jobs are removed after first run.

How can I make jobY be dependent on jobX in repeating scenarios.

**Comment by vsivsi** [comment]
Hi, thanks for this question.  Right now, there is no automatic way to do what you are describing.

One way to accomplish this would be to make jobX itself create a new dependent jobY each time it runs.  So only jobX repeats, but each time it repeats it creates a corresponding jobY.

The only drawback of this approach that I can see is that if running remotely, jobX needs to be trusted and given permission to create new jobs. However, the allow/deny rules can be tailored to only permit the user jobX is authenticated as to create jobY jobs. Obviously this drawback doesn't apply if jobX runs on the Meteor server itself.

**Comment by LarsBuur** [comment]
Thank you very much Vaughn.  I will try out the proposed solution.
