### ISSUE TITLE
.processJobs() not providing multiple jobs

### ISSUE THREAD

**Issue by leebenson** [vsivsi/meteor-job-collection#63]
v0.0.18

I'm building an e-mail queue that gets up to 10 messages per second (per worker).

However, even with "cargo" > 1, I'm still getting only a single job... and not an array of jobs as shown in the docs.

Example:

```
var jobOptions = {
    cargo: 10,
    pollInterval: 1000
};

Jobs.processJobs('email', jobOptions, function (jobs, finish) {
    console.log(jobs); <--- THIS IS NOT AN ARRAY!
});
```

Any ideas?

**Comment by vsivsi** [comment]
Thanks for filing his issue. I'll take a look at this tonight. -V

**Comment by vsivsi** [comment]
Hi, this appears to be a documentation issue, and I can't believe you are the first person to encounter it!  

The proper option parameter for `processJobs` is `payload: 10` not `cargo: 10`. Not sure how the docs diverged so much from the implementation, example code and unit tests.

I'll correct the documentation tonight, but I wanted to get you the answer quickly so you can verify that this is the issue on your end. You can see an example of how this is used here:

https://github.com/vsivsi/meteor-job/blob/master/test/index.coffee#L1346

**Comment by leebenson** [comment]
@vsivsi that's awesome, thanks so much!

Very surprised I'm the first to notice it too! I had to triple-check I didn't just fat-finger the variable name... seemed like such an obvious oversight that I _had_ to be doing something wrong... I guess everyone else just figured it out from the source.

Thanks again!

**Comment by vsivsi** [comment]
I've fixed this everywhere, so I'm closing this issue.  Thanks again for catching this!
