### ISSUE TITLE
Experimental support for later.js scheduling of repeating jobs

### ISSUE THREAD

**Issue by vsivsi** [vsivsi/meteor-job-collection#68]
I've implemented this on the laterJS branch: https://github.com/vsivsi/meteor-job-collection/tree/laterJS

Docs are here: https://github.com/vsivsi/meteor-job-collection/tree/laterJS#jobrepeatoptions---anywhere

Please give it a try and let me know how it works for you and if this is something you think should be released in v1.1

Also see discussion here...  https://github.com/CollectionFS/Meteor-CollectionFS/issues/236#issuecomment-85293461

**Comment by aldeed** [comment]
@vsivsi, cool looks good. How would it work if you want to schedule the job for a specific day/time in the future, repeating? It should not run immediately, so it would be like a combination of `after` + `repeat`.

```js
job.schedule(later.parse.text('at 3:00am every day'));
```

**Comment by vsivsi** [comment]
Hi, yes right now all of the other modifiers still apply.  So you need to use `after()` to delay the first run until the next time slot in the later.js schedule. 

```js
var sched = later.schedule(later.parse.recur().whenever())  // any schedule
var job = new Job(jc, type, data)
     .after(new Date(sched.next()))
     .repeat({ later: sched })
     .save();
```

I like the suggestion of adding a `schedule` method to Job to handle after and repeat in one call.  I'll think about that. If I do that, i may remove the `later` option from `repeat()`.  The repeat method does still have value though, because it allows you to set the number of times to run the job and/or an `until` time, to stop running.  Later.js doesn't seem to have a simple way to say "schedule this to run 100 times, once per hour", but maybe I've missed it. Also, setting hard start times and stop times with later.js seems cumbersome (requiring exception schedules and use of the before and after modifiers?)

**Comment by vsivsi** [comment]
There is another important behavior you should be aware of.  With job-collection, future repeating jobs are absolutely tied to the success of the most recent run of a job.  Or put another way, the repeat and retry functionality interact with each other. 

So if a scheduled job fails for any reason (or is cancelled), it stops all future repeated runs of that job. You can set the job to retry forever, and when it eventually succeeds, then it will run again at the next available future scheduled time. Or if the "failure" shouldn't impact future runs, then use `job.done()` with appropriate status rather than `job.fail()`. 

Anyway, it's worth noting that this is a little different from a cron-like system where the success or failure of a given run is irrelevant to the scheduling of future runs.

**Comment by aldeed** [comment]
@vsivsi, looks good. Yeah I saw the note in the docs about failure impacting future scheduling. Good to know about `job.done()`.

One alternative to adding `.schedule()` might be adding `.future()` so that one could do `job.future().repeat({ later: sched }).save()`, where "future" simply means "skip adding it to the queue right now and schedule the first repeat". I don't know if that makes any sense or is any better, but it popped into my head.

**Comment by vsivsi** [comment]
Okay, I just committed some changes:
`.repeat({ later: sched })` is now `.repeat({ schedule: sched })`

And behaviorally I've changed it so that when a `schedule` option is provided to `.repeat()`, the first run of the job will be delayed until the first valid scheduled time.  If `.after()` or `.delay()` have been used, then the first run will be the first valid scheduled time that occurs thereafter.  

As before the `until` and `repeats` options will also limit the number of times a scheduled job runs.

**Comment by aldeed** [comment]
Sounds perfect, thanks!

**Comment by vsivsi** [comment]
Great. I'm going to test this a bit more tonight and then I'll merge into the `dev` branch for inclusion in the 1.1 release.

**Comment by vsivsi** [comment]
Moved to `dev` branch

**Comment by vsivsi** [comment]
This released in version 1.1.0 last night.

**Comment by voidale** [comment]
@vsivsi Hello, I was looking at this package and wow it looks awesome! is it possible to send a job once in the future with a specific date? If for example I need to schedule social posts via API on customs dates is this package will be the right tool for this? I wasn't able to find concrete information about this. Thank you.

**Comment by vsivsi** [comment]
Yes, that is very simple, just use `job.after(new Date(someTime))` when scheduling the job.
See: https://github.com/vsivsi/meteor-job-collection#jobaftertime---anywhere

**Comment by voidale** [comment]
@vsivsi awesome thanks you very much.
