### ISSUE TITLE
Debugging jobPause failed messages

### ISSUE THREAD

**Issue by chmac** [vsivsi/meteor-job-collection#78]
Thanks again for this excellent package, it's simply brilliant.

I'm writing a little bootstrapping code to create a recurring job that should run every 6 hours. I have a crude check to see if the job already exists like `existingJob = myJobs.findOne type: 'foo'`. Then, if the job exists, I try `job = new Job myJobs existingJob` and then I try `job.pause()`. That throws the error "jobPause failed" in the console.

My hope was that by either creating a brand new job, or by pausing an existing one, I'd be able to set my default options and simply call `job.save()`, and in either state, the `.save()` would succeed. This way, if I ever change my job settings, any existing job should get updated with the new settings.

I found the that throws the "jobPause failed" message, but I'm not sure how to find the code path between my `job.pause()` call and that error message. Is it possible to get more info as to why a `.pause()` is failing? Any clues on how I could debug?

**Comment by vsivsi** [comment]
Hi, are you running `job.pause()` on the server or a client?  Where is the error being printed?

**Comment by vsivsi** [comment]
Actually now that I look at it, the error must be on the server, regardless of whether the method is called on the server.  That error is emitted if no jobs are actually paused. That can happen if the job no longer exists in the collection, or if the job is not in a `jobPausable` (waiting or ready) state.  From your description, the job should obviously exist because you just retrieved it with a `find`. Question is, what state is it in when you try to pause it?

**Comment by vsivsi** [comment]
One other tip: dealing with initializing an infinitely repeating job on server start is a common issue, and job-collection has a mechanism to deal with it:

```
job.save(
  {
    // Cancel any jobs of the same type,
    // but only if this job repeats forever.
    // Default: false.
    cancelRepeats: true
  }
);
```

This lets you "fire and forget" creation of repeating housekeeping jobs on server start, knowing that any existing jobs of the same type will automatically be cancelled.

**Comment by chmac** [comment]
Aha, you have me, I was just doing `findOne type: 'foo'` instead of also getting the `waiting` job. Also, your optimisation is exactly what I want instead, thanks. Outstanding support once again, thanks a lot.

**Comment by vsivsi** [comment]
You earned it with that pointer to the Meteor versioning issue. I have a feeling various flavors of that have been haunting the issues I've been fielding for months...  Sigh
