### ISSUE TITLE
job.getJob with getLog option throwing error

### ISSUE THREAD

**Issue by kingkevin** [vsivsi/meteor-job-collection#79]
I'm getting `Can't canonicalize query: BadValue Projection cannot have a mix of inclusion and exclusion` when fetching jobs with `jobs.getJob('vujZJF2mDc5gsynEA', {getLog:true})`

Still looking into the issue

**Comment by vsivsi** [comment]
I've got one more potential issue I'm looking into right now.  As soon as that is resolved (should be a couple of hours, tops ), I'll publish this to Atmosphere.  Thanks again!

**Comment by vsivsi** [comment]
Just published v1.1.3 with these changes.  Thanks again.
