### ISSUE TITLE
jc.startJobs() vs. jc.processJobs()

### ISSUE THREAD

**Issue by dandv** [vsivsi/meteor-job-collection#8]
The first example mentions starting "the myJobs queue running" with `myJobs.startJobs();`. I find this conceptually confusing vs. starting a queue with `jc.processJobs()`. What are the differences? Would it be possible to make `startJobs()` unnecessary in Meteor server code?

**Comment by rhyslbw** [comment]
The design makes complete sense, but I think the source of confusion here is the naming of `startJobs()`. I know this thread is 8 months old and the package is so close to 1.0, but reviewing the method name now may make a big difference for new users to understand this.

Considering the method is being chained to a collection that provides the context, I'd suggest `jobCollection.serve()` and  `jobCollection.shutdown()`. This associates the server concept without clashing with direct terminology already in use, and aligns with the Queue API where the same relative stop result is achieved.

**Comment by vsivsi** [comment]
@rhyslbw  You make good points above.  I'll consider renaming those for 1.0.0 (and deprecating the old versions).   Thanks.  -V

**Comment by rhyslbw** [comment]
:+1:

**Comment by vsivsi** [comment]
The dev branch of meteor-job and meteor-job-collection now implements these as:
`jc.startJobServer()` and `jc.shutdownJobServer()`. The old versions still work, but generate deprecation warnings.

**Comment by rhyslbw** [comment]
I'll test it out today. I also like the more verbose method names here. Unlike my serve() and shutdown() proposal, yours are not relying on the collection name for context.
