### ISSUE TITLE
Any advice on how to disable during tests?

### ISSUE THREAD

**Issue by chmac** [vsivsi/meteor-job-collection#81]
I'm finding that our jobs are running while I'm running `meteor test-packages`. It's not a huge issue, since the calls to `Email.send()` are logged to the console instead of being sent anyway, but I'd prefer to disable the jobs while tests are running if possible.

Any thoughts on how to do this? Build something into the `processJobs()` call maybe? I could add a check there to do nothing if meteor is running in test mode. Might be tricky to do so as to also be able to actually test the jobs, but I guess it's possible.

I wondered if you had a better solution?

**Comment by vsivsi** [comment]
Hi, that's strange. No jobs should run unless `jc.startJobServer()` has been run. Is that being executed somewhere in your test code? If so, I'd make sure that doesn't happen.

**Comment by chmac** [comment]
Aha, that makes sense, we can disable that call and all the jobs will be stopped. We're not explicitly running that in our test code, but our packages are being loaded by the tests, and that is run by one of the packages.

I had a look at `process.env` and I couldn't see any flags differed during a normal meteor run versus a test-packages run. I'll keep digging and disable that call once I find a way. Thanks.

**Comment by vsivsi** [comment]
Another way to solve this would be to ensure there are no workers available when tests are run.  That could be easy or difficult depending on where your workers are located (within app code, verses distributed in the cloud, etc).  Although not starting the JobServer would probably be best because that also prevents other side effects on the job collection. I assume that when testing you aren't running against your real production database, right?

**Comment by chmac** [comment]
We're not running tests against the production database. They're mostly run on CircleCI, and locally in dev.

I suppose my next question is, how do I tell if Meteor is running in test or not? Is there some kind of `process.env` flag set?

Is that the best practice solution? Some conditional in front of the call to start the job server, so that if we're running under test, it doesn't get started? I feel like there should be a way to tell meteor to stub the whole package, but I can't quite figure that out. I think Velocity does something like this for application code, but we're building the app entirely in packages, ironically, because it has (had?) better testing support! :-)

**Comment by vsivsi** [comment]
In the pure node.js world this is the usual province of npm packages like [sinon](https://www.npmjs.com/package/sinon) and [rewire](https://www.npmjs.com/package/rewire).

i don't know the status of using these (or equivalent) packages to test whole Meteor applications. In general, I think you are right that splitting an app into packages should make it much easier to test and obtain high levels of code coverage.

Anyway, good luck. And please take a moment to report back when you figure out a solution the meets he needs of your project.

**Comment by vsivsi** [comment]
If you search for "sinon" on atmosphere, you will find several packages porting it into the Meteor environment. I can't vouch for any of these, but thought I'd mention that others are apparently using it in the Meteor context.

**Comment by chmac** [comment]
Sinon is great. I'm using it by just importing the npm package and then exporting it. We have an `app-testing` package, where we `api.use()` and `api.imply()` our test dependencies, and export chai's `expect()`, `assert()`, etc.

We also have an `app-jobs` package, which instantiates a `JobCollection` and so on. The problem is, if my package `foo` depends on `app-jobs`, then when I run test-packages against `foo`, it will load the `app-jobs` package, but not under test, as normal, and so it the `JobColllection` will be started.

If I could figure out when meteor was running `test-packages`, I could build that logic into my code. Somehow that seems like the wrong pattern though.

Maybe the solution is that my packages only expose functionality, they don't start anything. Then somewhere in my meteor application I call some kind of `app.start()`, which triggers all of my packages to actually start running.

Or, I could simply abandon the whole idea of building my entire app as packages, and just expose functionality from packages when I need to control load order, and so on. It seems like testing support has gotten much better for app code thanks to Velocity.

I've now deviated quite far off topic from the job collection package! @vsivsi as always, thanks for the excellent advice.
