### ISSUE TITLE
Is it possible to enforce serial job execution?

### ISSUE THREAD

**Issue by chmac** [vsivsi/meteor-job-collection#85]
I read #77 and was about to reply there, but I realise that serial execution is not strictly required for a FIFO job queue. (Although I think @randomnerd is looking for FIFO + serial in #77).

Is it possible to ensure that jobs are only ever executed in serial? I re-read the docs and didn't spot an obvious answer.

With a single worker and `concurrency: 1`, jobs would be executed in series. So my question could be rephrased as, is there any way of ensuring only a single worker exists on a JobCollection?

Effectively I'm trying to hijack JobCollection to create a system wide mutex, that could span multiple Meteor nodes. I realise it's not really the package's purpose, so feel free to give me a straight "no" as an answer. :-)

Again, @vsivsi thanks for this excellent package that I seem to be solving more and more of my meteor challenges with. If you're ever in Berlin, drop by our Meteor meetup and give us a talk! :-)

**Comment by vsivsi** [comment]
Hi @chmac, well job-collection was really designed to make it easy to *parallelize* execution of many jobs, so you are asking for a bit of the opposite of the ordinary use case here!

To **enforce** serial (but not necessarily FIFO) execution of a given job type in a job-collection when there may be multiple servers and/or independent workers, you will indeed need some kind of Mutex.  Fortunately for you, I have already solved this problem with my [gridfs-locks npm package](https://www.npmjs.com/package/gridfs-locks). Don't let the name fool you, it is not tied to use with gridFS, you may use it for any purpose. 

For example, I use it in my file-collection package to ensure that only one execution Fiber can ever begin the process of assembling the chunks of a given uploaded file: https://github.com/vsivsi/meteor-file-collection/blob/master/src/resumable_server.coffee#L21

It has been heavily tested in the gridfs / file-collection application and performs well.  I recommend you try it!

**Comment by chmac** [comment]
Vaughn Iverson strikes again! I think from now on my response to every Meteor challenge will be to ask, how has @vsivsi already solved this problem for me! :-)

I had a quick look at gridfs-lock and it looks like exactly what we need. I'll dig into the code in the next few days. Thanks again.

**Comment by vsivsi** [comment]
@chmac You flatter me! At a minimum I will permit you to buy me a Currywurst and a Berlinerweißbier next time I'm in Berlin. Love that town! :beers:

I hope the locking solution works our for you!  Let me know if you have any questions.  It might be nice to wrap that npm lib up in a Meteor package at some point, but I haven't needed that yet myself so the priority has low.
