### ISSUE TITLE
Simple setup of a job running a function every x minutes only available for server

### ISSUE THREAD

**Issue by miri-am** [vsivsi/meteor-job-collection#90]
Not an issue but a question: I am trying to setup something very simple and maybe somebody can just give me a quick hint.  I have a function that updates multiple documents in a collection called "checkExpiredDocuments". I want this function to run every 2 minutes forever, persisting server restarts.

Is this the correct setup for my requirement? Do I need the queue, is the ` //EXECUTE THE DESIRED FUNCTION TO RUN HERE` placed correctly?  

I have the feeling I am overcomplicating things.

This is what I am currently doing: 
```
//file sever.js
var myJobs = JobCollection('defaultJobCollection'); //create job collection

myJobs.deny({
  admin: function (userId, method, params) {
    return true; //only allow server to use job collection
  }
});	

//create a job. Does not need data
var job = new Job(myJobs, 'checkExpiredDocuments', {});
job.repeat({
    schedule: myJobs.later.parse.text('every 2 mins')   // Rerun this job every minute
});
job.save({cancelRepeats: true});

Meteor.startup(function() {
    myJobs.startJobServer();
    var queue = myJobs.processJobs(
        'checkExpiredDocuments', {},
        function (job, callback) {
          //EXECUTE THE DESIRED FUNCTION TO RUN HERE (is this correct)
           job.done();
	   callback();
     });
});

**Comment by vsivsi** [comment]
Hi, sorry for the delay... busy week.  Yes, that looks about right.  If you truly just want a job that runs every two minutes, then there's no need to resort to using later.js to schedule it (although that will work).

You could just as easily use:
```js
var job = new Job(myJobs, 'checkExpiredDocuments', {}).repeat({ wait: 2*60*1000 });
var result = job.save({cancelRepeats: true});
```
The `myJobs.deny()` isn't necessary, as job-collection is completely locked-down by default.

The only other missing bit (assuming you just left it out for clarity) is error handling. If your "desired function" can fail in any way (either by throwing or returning an error), then your worker function should probably use `job.fail(err)` with the returned/caught error so it will be logged.

In that case, you'll also need to set-up the job to [auto-retry](https://github.com/vsivsi/meteor-job-collection#jobretryoptions---anywhere):

```js
var job = new Job(myJobs, 'checkExpiredDocuments', {})
     .repeat({ wait: 2*60*1000 })
     .retry({ wait: 2*60*1000 })
var result = job.save({cancelRepeats: true});
```
Hope that helps.

**Comment by miri-am** [comment]
Thanks. Extraordinary support!
