### ISSUE TITLE
How to stop the endless 'getWork, returned: []' messages ?

### ISSUE THREAD

**Issue by petrometro** [vsivsi/meteor-job-collection#91]
I really appreciate the work done on this package, it fills a huge gap in the package landscape and works great over ddp !

My one complaint is the huge log noise that it churns out, every 5 seconds 'getWork, returned: []'...

How exactly does one reduce the log level ? I would of course like to keep the error and other messages...

**Comment by vsivsi** [comment]
Hi, this is fully under your control via the [`jc.setLogStream()` call](https://github.com/vsivsi/meteor-job-collection#jcsetlogstreamwritestream---server-only)

My guess is that somewhere in your code you are calling it, e.g.:

```
jc.setLogStream(process.stdout);
```

Either eliminate that call completely, or open a log file for writing and pass file's the input stream instead.

Hope that helps!

**Comment by petrometro** [comment]
great thanks ! is there any way to set log levels ?

**Comment by vsivsi** [comment]
That log is specifically the full DDP / method call dump, for debugging/monitoring purposes. Because it just emits a stream, you can write your own node.js stream filters to remove or add anything you'd like before printing or writing it to a file. 

Each individual job has its own event log which does have levels, but those live in the collection itself.

**Comment by petrometro** [comment]
ok thanks for the info !

**Comment by vsivsi** [comment]
One other bit of info I forgot to mention...

It is easy to override the function that for,as the DDP traffic log.  So it is simple to change the format of the messages, or to add tests to filter a thing out, or to only include hints of specific interest:

https://github.com/vsivsi/meteor-job-collection/blob/master/src/server.coffee#L71
