### ISSUE TITLE
Polling vs Triggering

### ISSUE THREAD

**Issue by skosch** [vsivsi/meteor-job-collection#94]
Sorry, I have another ignorant question (or rather, request for documentation)!

I would like to understand why the queue can't listen for a trigger message via DDP instead of polling the database every n seconds. I'd love to use the `trigger`/`observe` pair, but my workers are simple node scripts and don't understand Meteor. Clearly, I'm misunderstanding how DDP works—if workers can send updates to the server, can't the server broadcast "hey, someone pick up this job please?"

**Comment by skosch** [comment]
Ah, I found the right spec now. DDP doesn't let servers broadcast anything. That's a shame. Is there another way? Could you comment on how much extra overhead it would be to teach my dumb worker scripts to understand `observe`?

**Comment by vsivsi** [comment]
The npm [DDP package](https://www.npmjs.com/package/ddp) which you are presumably using allows you to subscribe to a record set and write callbacks similar to `cursor.observe()` in Meteor.

Search for: `ddpclient.observe("posts");` in the documentation on the linked npm page above for an example of how it works.  Using that you can write an `observer.changed` handler to look for suitable jobs becoming ready and call `q.trigger()`

**Comment by skosch** [comment]
Amazing. Thanks. Once I get that to work I'll send you a PR for the documentation with a piece of example code (and also one for #93) :)

**Comment by rhyslbw** [comment]
This can be closed
