### ISSUE TITLE
Node.js worker for vsivsi/meteor-job-collection fails on job.done(): "Exception while invoking method 'jobs_jobDone' Error: Match error..."

### ISSUE THREAD

**Issue by danholten** [vsivsi/meteor-job-collection#98]
Hi all,

First of all, thanks for the library - I got it integrated without any problems, but I'm having an issue when using external (Node.js-based) job workers (I posted this on stackoverflow as well: http://stackoverflow.com/questions/31658421/node-js-worker-for-vsivsi-meteor-job-collection-fails-on-job-done-exception).

I'm developing a Meteor app that adds jobs to a queue that are to be processed by one or more external workers. I'm using vsivsi/meteor-job-collection and everything worked fine when I was (initially) processing jobs using method-based (i.e., non external) workers from within the Meteor app itself (which queues, creates, and manages the jobs).

However, I want an external process, i.e., a Node.js program (not even a Meteor app) to listen for and subsequently process posted jobs instead and saw that this is indeed possible at https://github.com/vsivsi/meteor-job-collection#quick-example (third code block; "node.js Worker") - after all, this enables a more generic and Meteor-agnostic job-processing approach.

I created a separate Node.js program, successfully connected it to my running Meteor app using your example code and started the job listener in exactly the same fashion as I originally did within the Meteor app (when using method-based workers), but I get the following inexplicable error (only) when calling job.done() (other job methods seem to work flawlessly):

**"Exception while invoking method 'jobs_jobDone' Error: Match error: Failed Match.OneOf or Match.Optional validation"**

I should add that calling job.done() from my original (method-based, in-app workers) worked perfectly as well. The code:

    var DDP = require('ddp');
    var DDPlogin = require('ddp-login');
    var Job = require('meteor-job');
    var ddp = new DDP({
        host: "localhost",
        port: 3000,
        use_ejson: true
    });

    Job.setDDP(ddp);
    ddp.connect(connectCB);

    function connectCB(err) {
        if (err)
            throw err;
        var options = {
            env: 'METEOR_TOKEN',
            method: 'account',
            account: null,  
            pass: null,     
            retry: 5,       
            plaintext: false
        };
        DDPlogin(ddp, options, ddpLoginCB);
    }

    function ddpLoginCB(err) {
        if (err)
            throw err;
        Job.processJobs('jobs', 'dataGatherJob', {
            concurrency: 8,
            pollInterval: 250
        }, processJobsCB);
    }

    function processJobsCB(job, cb) {
        //This callback works fine, is triggered when my Meteor app adds a new job,
        //and the job object conforms to my expectations; just some example calls on
        //(usages of) the job object that work fine and are reactively updated and
        //handled by my Meteor app:
        //console.log(job); //Works fine.
        //job.progress(50, 100); //Works fine.
        //job.fail(); //Works fine.
        job.done(); //Causes the Meteor-app (server) to generate an "Exception while invoking method 'jobs_jobDone' Error: Match error: Failed Match.OneOf or Match.Optional validation" error.
        cb(); 
    }   

I do not understand why this is happening. The job id is identical to the one in the actual Mongo collection set by the server (I checked this) and as stated earlier, other job operations (e.g., job.fail()) do work. I furthermore reset the "autopublish" and "insecure" packages for my Meteor app intermittently just to be sure that they are not causing the problem and this was not the case.

Any thoughts on this?

Many thanks in advance,
Danny.

**Comment by danholten** [comment]
**Update**: adding a result parameter to job.done() doesn't make a difference; when using the job.done("Done!") example at https://www.npmjs.com/package/meteor-job#j-done-result-options-callback the error is the same.

In the meantime I solved/circumvented the problem by simply delegating a job.done-call to the server by remotely calling a Meteor.methods({ ... })-exposed method through DDP within the processJobsCB function (instead of calling job.done() there), i.e.: ddp.call('setJobDone', [job._doc._id], function(err, result) { ... }, function() { ... }) as in https://www.npmjs.com/package/ddp#example. This gets the job done for now (quite literally).
	
    Meteor.methods({
        setJobDone: function(jobID) {
            jobs.getJob(jobID, function(err, job) {
            if (job)
                job.done();
            });
        }
    });

**Comment by vsivsi** [comment]
What versions of job-collection are you running on your server? And what version of the meteor-job npm package are you running on your client?

**Comment by vsivsi** [comment]
Here's my guess what is happening... Your server is running 1.1.x (current is 1.2.1) but your node client is running the most up-to-date 1.3.0 npm package.  An optional feature was added to `job.done()` on the server in 1.2.0.  You can always use older versions of the npm package with newer servers, but the opposite isn't true. Newer clients may attempt to use features that the older servers don't support. In this case, I shouldn't be setting that new option automatically to it's default (non-active) state in the npm packages. That's my mistake and I'll fix it in the npm package today so nobody else gets bit by this.

You should be able to resolve this immediately by either updating the server to job-collection 1.2.1 or downgrading the npm package to meteor-job@1.2.0.

**Comment by danholten** [comment]
Thanks a lot! I will be trying this as soon as I'm back later today. Hope it helps.

**Comment by vsivsi** [comment]
Or you can bump the npm meteor-job package to the latest (just released) version 1.3.1, which refrains from setting a default value for the optional `repeatId` parameter on `job.done()` that 1.1.x servers don't support.

I should probably get the version numbers of meteor-job and job-collection back in sync so I can state a simple rule like: always use major.minor versions of meteor job that are equal to or older than the version of job-collection that is running on your server. As it is, you need to look and see which version of meteor-job is bundled with your server to know what newer versions may be incompatible which is definitely suboptimal.

**Comment by vsivsi** [comment]
@danholten  Did one of my suggestions above clear this up for you?

**Comment by danholten** [comment]
Hi Vaughn,

Bumping to 1.3.1 in my Node.js monitoring program did the trick; I can now call job.done() without problems. Much appreciated!

Best,
Danny.

**Comment by vsivsi** [comment]
Great thank for reporting back!
